### ISSUE TITLE
-W not run attack...

### ISSUE THREAD

**Issue by FightingForFun** [t6x/reaver-wps-fork-t6x#116]
reaver -i wlan0mon -c 1 -b C8:6C:87:3E:01:00 -vv -K 1 -W

Reaver v1.5.3 WiFi Protected Setup Attack Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>
mod by t6_x <t6_x@hotmail.com> & DataHead & Soxrok2212 & Wiire & AAnarchYY & KokoSoft

[+] Switching wlan0mon to channel 1 <!--- WHAT IS THAT ?
Required Arguments:
	-i, --interface=<wlan>          Name of the monitor-mode interface to use
	-b, --bssid=<mac>               BSSID of the target AP

---
Some problem in -W...  
If possible make pin generator as default attack.

**Comment by kcdtv** [comment]
> Some problem in -W...

You need to indicate a number after -W ( 1 or 2 or 3)
`-W, --generate-pin              Default Pin Generator [1] Belkin [2] D-Link [3] Zyxel`

> If possible make pin generator as default attack.

Default PIN is 12345670 for a reason: That's the PIN configured automatically for a device when it firmware has WPS enabled but the PIN is not correctly defined. I am speaking about building time. That is why you can find in many Brant some routers with 12345670 as a default PIN.  
I think it is kind of logical to have it as a first PIN, it could happen at anytime.
Than if the user has a d-link or Belkin device (he should be aware and if not it is not difficult to check in a OUI table) he might prefer to use the generator. 
I am quite OK with that... Why would we use first a PIN that for sure won't work for other models than belkin (for example)? 12345670 is a good shot in any case.
