### ISSUE TITLE
Implementation on Wemos D1 mini pro

### ISSUE THREAD

**Issue by nisc3** [t6x/reaver-wps-fork-t6x#125]
Is it possible to implement on esp8266 chip? Wemos D1 mini pro got 16MB of storage, supports monitor mode, has an external antenna connector, supports packet injection, it can be programmed through arduino IDE.

**Comment by kcdtv** [comment]
The answer is the same than here: [https://github.com/wiire/pixiewps/issues/40](url) 
You need full packet injection, not "a kind of" injection.
