### ISSUE TITLE
Add weak default pin attack for certain router models

### ISSUE THREAD

**Issue by crass** [t6x/reaver-wps-fork-t6x#126]
Some [Belkin](http://www.devttys0.com/2015/04/reversing-belkins-wps-pin-algorithm/) and [D-Link](http://www.devttys0.com/2014/10/reversing-d-links-wps-pin-algorithm/) routers use weak default pins.  I can envision a couple different ways of doing this, from detecting the router make/model and specifically applying a weak pin for that specific make/model to reordering the pin space such that the weak keys generated for all known routers are at the beginning of the space.

**Comment by soxrok2212** [comment]
This is already implemented with the -W argument.
