### ISSUE TITLE
memory leaks?

### ISSUE THREAD

**Issue by 1yura** [t6x/reaver-wps-fork-t6x#134]
Hello! valgrind --leak-check=full says
> ==21094== HEAP SUMMARY:
==21094==     in use at exit: 2,525 bytes in 28 blocks
==21094==   total heap usage: 16,323 allocs, 16,295 frees, 532,737 bytes allocated
==21094== 
==21094== 8 bytes in 1 blocks are definitely lost in loss record 1 of 8
==21094==    at 0x402A17C: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==21094==    by 0x804B8B2: set_ap_rates (globule.c:617)
==21094==    by 0x804E85C: parse_beacon_tags (80211.c:554)
==21094==    by 0x804EA47: read_ap_beacon (80211.c:116)
==21094==    by 0x804EA88: reassociate (80211.c:240)
==21094==    by 0x804CBD4: crack (cracker.c:173)
==21094==    by 0x8049BEC: main (wpscrack.c:115)
==21094== 
==21094== 570 bytes in 5 blocks are definitely lost in loss record 7 of 8
==21094==    at 0x402A17C: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==21094==    by 0x804FACB: build_eap_packet (builder.c:361)
==21094==    by 0x804D8A9: send_msg (send.c:113)
==21094==    by 0x804D91A: send_wsc_nack (send.c:153)
==21094==    by 0x804F190: do_wps_exchange (exchange.c:299)
==21094==    by 0x804CBE0: crack (cracker.c:191)
==21094==    by 0x8049BEC: main (wpscrack.c:115)
==21094== 
==21094== 1,920 (1,200 direct, 720 indirect) bytes in 5 blocks are definitely lost in loss record 8 of 8
==21094==    at 0x402A17C: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==21094==    by 0x804BA34: initialize_wps_data (init.c:69)
==21094==    by 0x804CB74: crack (cracker.c:149)
==21094==    by 0x8049BEC: main (wpscrack.c:115)

about last section: In the file init.c in the function initialize_wps_data there is
wpsconf->wps->registrar = wps_registrar_init(wpsconf->wps, (const struct wps_registrar_config *) reg_conf);
but there is no pair "wps_registrar_deinit()". And wpsconf->wps = malloc(sizeof(struct wps_context)); hasn't pair "free()". Probably we need to save the pointer wpsconf together with "globule->wps" and destroy it all together;
Update.
In file send.c, function send_msg
>        packet = build_eap_packet(payload, payload_len, &packet_len);
        if(packet)
        {
            if(send_packet(packet, packet_len))
            {
                ret_val = 1;
            } else {
                free((void *) packet);
            }
        }

i suggest to rewrite:
>        packet = build_eap_packet(payload, payload_len, &packet_len);
        if(packet)
        {
            if(send_packet(packet, packet_len))
            {
                ret_val = 1;
            }
            free((void *) packet);
        }

**Comment by rofl0r** [comment]
did you test if your suggested fix actually works ? the packet data may be used later on.
also i want to point out that this is not quality software, and we're quite aware that there are some leaks. it's only problematical if that happens in a loop though, i.e. it would mean that if you run a long bruteforcing session there would be more and more memory used over time.
