### ISSUE TITLE
packaging (feature) request.

### ISSUE THREAD

**Issue by zifxify** [t6x/reaver-wps-fork-t6x#152]
There's a possibility to make use of an automated packaging system to provide installable packages for different distro's like the openSuSe Build Service (https://build.opensuse.org/) which currently supports not only openSuse,Fedora but also Debian and derivatives like xUbuntu. 
Instead of (re)compiling or trusting someone else's binaries, this could be a great alternative (in my opinion).

**Comment by kcdtv** [comment]
> Instead of (re)compiling or trusting someone else's binaries, this could be a great alternative (in my opinion).

  
  Git Hub is safe and it is as reliable as others repositories. 
There is no risk of compiling somebody else binaries if you use this repository with git command line
If you do not use the git command line you have sha and md5 to check the integrity of the downloaded tarball package 
  Having it packed doesn't make it safer intrinsically . 

 The problem with packaging is that it takes time and maintenance 
  Beside that, reaver 1.4 is already in the repositories of a lot of distributions
It seems to me a better idea to get reaver 1.6.x into this distributions repositories. 
  Let the distribution maintain their repository and we can focus on others challenges... 
Saying so, if you want to do a package in a format and maintain it, we could add it I guess.... 
Cheers
