### ISSUE TITLE
failed to recover wpa key

### ISSUE THREAD

**Issue by Robiii97** [t6x/reaver-wps-fork-t6x#153]
I get the error reaver failed to recover wpa key after 1 crack attempt.
This happens right after receiving and sending m1 m2 m3 m4 message's

Any solution?

**Comment by kcdtv** [comment]
We need to know the precise command line you used and to see the stdout (what happens in the shell) 
So... copy and paste what happens in the shell. 
  It doesn't look like an error; it looks like you used an arbitrary string or -Z or -g 1.
