### ISSUE TITLE
Compile for OpenWrt?

### ISSUE THREAD

**Issue by mile18** [t6x/reaver-wps-fork-t6x#155]
Could you post makefile update for new 1.6b version, or explain how to compile it for OpenWrt?

**Comment by rofl0r** [comment]
the makefile is already updated. the build works as it always did:
```
./configure --prefix=/usr --enable-savetocurrent
make -j2
make install
```

**Comment by vido89** [comment]
```
git clone https://git.lede-project.org/source.git lede
cd lede

./scripts/feeds update -a
./scripts/feeds install -a

make menuconfig
```

Mine device is AR7XXX - TP-Link MR3220

Reaver is under Network->Wireless
