### ISSUE TITLE
WPS transaction failed (code: 0x03), re-trying last pin

### ISSUE THREAD

**Issue by PalexM** [t6x/reaver-wps-fork-t6x#158]
Hello , 
I have been seeing this problem for a while and i dont know more about this .Can anyone explain what really happens and why does not it go to another pin?
Best regards

**Comment by rofl0r** [comment]
probably too far away, or not the right chipset...

**Comment by PalexM** [comment]
I use alfa AWUSO36H and power is under 50 ,  the wps is not block when i check with wash -i

**Comment by soxrok2212** [comment]
PWR levels don't matter, RXQ is the important factor. Could also have a fake 036H, lots of interference, bad USB creating interference, bad/old/corrupted drivers, there is no concrete answer.

**Comment by PalexM** [comment]
How i know that is a fake alfa card ? The card is act good , i have a good signal
