### ISSUE TITLE
Request: Update Big_endian branch to version 1.6b

### ISSUE THREAD

**Issue by adde88** [t6x/reaver-wps-fork-t6x#161]
Hi there. and thanks for the awesome work! Especially the latest version bump!
It would be awesome if the Big_endian branch could be updated to version 1.6b.
So that we could compile the newest Reaver for OpenWRT. 👍 

The hak5 community would definitely be happy:
https://forums.hak5.org/topic/41649-install-reaver-v161-null-pin-on-wifi-pineapple-nano/?tab=comments#comment-295945

**Comment by kimocoder** [comment]
@kcdtv what do you say? is it on the future todo list? im home from holidays & may take a look at it too :)

takk for forespørselen, jeg tar en kikk på det nå i helga :)

**Comment by adde88** [comment]
Thank you very much for such a quick response!
If there's anything i can do to help, let me know :)

**Comment by PineNappler** [comment]
This would very useful for me and others i know. Would be great to have! 👍

**Comment by kimocoder** [comment]
well, feel free to start porting code from 1.6b repo to the big_indian one if the knowledge of howto is in place. dunno yet if it needs modifications, we'll see

**Comment by rofl0r** [comment]
huh ? why would you want that ? you can just use the latest release and it'll work on openwrt with big and little endian.

**Comment by adde88** [comment]
@rofl0r 
Attempting to compile the latest commit with the Openwrt-SDK gives the following error-messages:
```
{standard input}: Assembler messages:
{standard input}:20: Error: unrecognized opcode `wsbh $2,$4'
{standard input}:780: Error: unrecognized opcode `wsbh $2,$2'
{standard input}:781: Error: unrecognized opcode `rotr $2,$2,16'
{standard input}:806: Error: unrecognized opcode `wsbh $4,$4'
{standard input}:807: Error: unrecognized opcode `rotr $4,$4,16'
{standard input}:889: Error: unrecognized opcode `wsbh $3,$2'
{standard input}:890: Error: unrecognized opcode `rotr $3,$3,16'
<builtin>: recipe for target '80211.o' failed
```

A full error-message can be found here:
https://pastebin.com/5P94AsVE

**Comment by adde88** [comment]
This can now be closed, i managed to get it compiling. :)
