### ISSUE TITLE
error: pcap library not found!

### ISSUE THREAD

**Issue by armulixor** [t6x/reaver-wps-fork-t6x#162]
when .\configure, i got this error : 
error: pcap library not found!

config : debian buster
libpap is installed

**Comment by adde88** [comment]
have you tried to compile and install libpcap manually?

**Comment by kimocoder** [comment]
there a difference to having "libpcap" and "libpcap-dev" installed.. what you need is the "libpcap-dev" to compile

**Comment by soxrok2212** [comment]
Please stop re-opening the same issue over and over. Read the documentation.
