### ISSUE TITLE
new release tag for json option support

### ISSUE THREAD

**Issue by anthraxx** [t6x/reaver-wps-fork-t6x#165]
Hey, thanks for the work. any chance we can get a new git tag soonish that includes the json option feature? :smirk_cat: 
cheers

**Comment by rofl0r** [comment]
yes, i think that feature definitely deserves a release. i hope the team will have time tonight to meet in IRC so we can prepare it together.

**Comment by anthraxx** [comment]
w00h00 release party :tada: :balloon: :smirk_cat: 
thanks a lot

**Comment by kimocoder** [comment]
There we got it 👍 thanks @rofl0r

**Comment by rofl0r** [comment]
it was teamwork. ;)

**Comment by anthraxx** [comment]
woohoo thanks to the team :smile_cat:
