### ISSUE TITLE
Wash wont work with both -j (JSON output) & -o (write to file) parameters together

### ISSUE THREAD

**Issue by DJDan** [t6x/reaver-wps-fork-t6x#170]
I cant seem to use wash -i mon0 -j (json output) with the -o outputfile.txt 
It wont output anything to the file.  (eg; wash -i mon0 -j -o outputfile.txt )
This should display the -j Json output to screen, while saving it to file.

Improvement:
Also, Maybe have a -o output option, that will output the json data to a port that is accessible via the network too.

**Comment by rofl0r** [comment]
> Also, Maybe have a -o output option, that will output the json data to a port that is accessible via the network too.

you mean as in `wash -i mon0 -j | nc -l -p 6666`

**Comment by rofl0r** [comment]
can you test if my commit fixed it pls ?
