### ISSUE TITLE
Reaver Problem : WPS transaction failed (code: 0x04), re-trying last pin. Please HELP !!

### ISSUE THREAD

**Issue by Ghostfro** [t6x/reaver-wps-fork-t6x#172]
Hi everyone,
im trying to get the pin of an AP, but i have this problem, 
Reaver WPS Transaction Failed (code: 0x04 ), retrying last pin.
and it repeats the first pin : "12345670"
so it's stuck at 0%
The PWR is good  "-55" , it's a WPA2 protected AP, i already tryed Pixiewps and the attack fails so i wanted to get the pin with only reaver.
the injection is 100% on this ap when i tested it with aireplay, and the wireless card is totaly working with other AP's so it's not a wireless card problem " it's an Alfa AWUS036H " 
i searched so much in google, still didnt found any solution so far.
The AP is a Technicholor as u can see 
can anyone help me ? thx :)

wifislax64 ~ # airmon-ng start wlan0

Found 3 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to kill (some of) them!

PID     Name
1855    NetworkManager
2327    wpa_supplicant
2357    dhclient

Interface       Chipset         Driver

wlan0           Realtek RTL8187L        rtl8187 - [phy0]
                                (monitor mode enabled on mon0)

wifislax64 ~ # airmon-ng check kill

Found 3 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to kill (some of) them!

PID     Name
1855    NetworkManager
2327    wpa_supplicant
2357    dhclient
Killing all those processes...
wifislax64 ~ # 

 CH 10 ][ Elapsed: 6 s ][ 2017-10-10 22:48                                         
                                                                                                                          
 BSSID              PWR  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID
                                                                                                                          
 C4:EA:1D:1F:5A:67  -55        7        0    0  11  54e  WPA2 CCMP   PSK  TNCAP1F5A67                                     
 FE:98:66:99:E6:79  -59        9        0    0   1  54e  WPA2 CCMP   PSK  SALIHA                                          
 18:D6:C7:7F:AC:44  -63       11        0    0   9  54e. WPA2 CCMP   PSK  <length:  0>                                    
 00:19:70:38:FF:6F  -69        2        0    0   1  54e. WEP  WEP         ADSL5272                                        
                                                                                                                          
 BSSID              STATION            PWR   Rate    Lost    Frames  Probe                                                
                                                                                                                          
 (not associated)   50:F0:D3:46:11:FC  -67    0 - 1      0        2  TNCAP1F5A67
 
 
 
 wifislax64 ~ # reaver -i mon0 -b C4:EA:1D:1F:5A:67 -c 11 -vvv 

Reaver v1.5.4 WiFi Protected Setup Attack Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>
t6_x <t6_x@hotmail.com> & DataHead & Soxrok2212 & Wiire & AAnarchYY & KokoSoft fork
MOD by vk496 for www.seguridadwireless.net

[+] Switching mon0 to channel 11
[+] Waiting for beacon from C4:EA:1D:1F:5A:67
[+] Associated with C4:EA:1D:1F:5A:67 (ESSID: TNCAP1F5A67)
[+] Starting Cracking Session. Pin count: 0, Max pin attempts: 11000
[+] Trying pin "12345670"
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[P] E-Nonce: 96:8f:52:b3:cc:a9:8e:d3:c6:e3:47:a5:f5:cc:37:1e
[P] PKE: 1e:52:4a:4c:03:55:c4:b5:f0:8f:2d:dc:f2:69:80:0e:f5:55:c8:0e:3b:cf:f5:3f:74:23:d8:a0:21:4b:0a:3b:2b:74:d4:b7:64:13:d6:2f:17:b7:1c:b1:f3:b0:51:2a:50:d8:50:91:3d:0b:fb:24:2f:c6:04:ff:e4:42:be:61:ed:5f:4b:57:96:6a:36:38:63:36:a6:4d:9a:ae:2f:97:27:ae:44:c5:37:50:b0:76:dd:5b:bc:af:2f:43:8f:fe:a1:cf:93:78:fb:0a:72:7d:a2:58:98:dd:62:51:31:ef:52:2d:73:48:4d:11:34:a2:77:2b:b6:f7:06:3b:b0:12:c8:b1:f8:f5:a9:ff:34:40:30:3f:b6:69:1e:32:eb:18:77:f8:92:09:84:e9:41:10:c0:c6:93:58:1a:20:5a:f1:c4:3e:c6:c2:26:e3:ec:eb:b2:90:17:4c:16:72:a1:90:c5:3a:be:cb:95:85:a5:9e:2f:b3:39:05:4d:80:1c:30
[P] WPS Manufacturer: Technicolor
[P] WPS Model Name: MediaAccess TG
[P] WPS Model Number: 799vn v2
[P] Access Point Serial Number: 1528CS3J9
[+] Received M1 message
[P] R-Nonce: 15:3f:07:5f:94:45:58:ec:c9:3b:e8:b8:bf:fe:e9:89
[P] PKR: 24:72:dc:56:f1:c2:b2:f5:b9:72:d0:70:e7:fd:85:55:3b:fc:65:bc:7b:e3:d2:87:14:b6:1d:a9:18:d9:7c:f9:0c:bb:67:25:f3:db:4d:d6:5a:54:26:99:9b:3c:d3:07:9f:50:3b:84:8f:e5:01:21:ac:0c:54:0a:3a:e3:92:05:17:6f:b8:cd:8e:e8:21:ca:77:e7:51:a4:13:9c:42:53:a7:1e:f6:74:4a:39:52:78:df:d8:61:07:8e:a6:d6:33:38:ff:f3:d4:6d:ee:0f:ff:79:28:38:f6:55:f4:8f:2b:9d:17:41:24:3b:63:49:a2:d6:08:f2:67:7a:30:ff:14:e2:f4:45:d0:81:cf:28:e2:d6:25:d5:15:e3:a6:2d:a5:bc:57:4f:49:f1:3e:2a:c1:fb:8e:8d:ac:f9:d9:41:aa:03:9b:24:f3:b1:cb:d3:e8:80:86:3c:8e:87:c5:02:e0:b6:4e:87:af:de:fd:a8:b0:a1:d1:d4:29:09:39:de:18
[P] AuthKey: 08:a5:25:f5:c7:7b:24:43:ee:8f:b7:99:a4:2a:63:7d:6c:b7:e8:7f:3a:c6:8b:e3:5a:b1:25:d1:12:15:18:00
[+] Sending M2 message
[+] Received WSC NACK (reason: 0x000F)
[+] Sending WSC NACK
[!] WPS transaction failed (code: 0x04), re-trying last pin
[+] Trying pin "12345670"
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[P] E-Nonce: 3d:60:ae:11:a3:5e:2e:40:73:bd:08:c2:95:01:15:9c
[P] PKE: 3c:4a:4e:3a:de:be:9a:4d:d0:da:81:07:21:30:a5:0e:93:2b:51:43:0a:73:17:56:2e:92:64:c3:c6:aa:03:70:a0:ad:da:d3:d3:4d:08:36:12:7f:51:5b:af:78:99:eb:1c:0f:ec:81:62:7d:ac:b6:51:48:74:4e:56:20:10:44:62:a1:89:0d:73:1f:65:c0:8f:7c:0a:74:6c:5c:44:7b:6a:fb:7e:e9:b2:39:2a:26:65:5c:de:88:3a:d0:aa:84:43:6a:df:9d:42:64:40:7f:47:ef:2f:bb:23:b8:e9:25:67:d1:25:5b:01:89:63:33:6f:8e:d1:5e:dd:3f:a0:ff:d0:2c:e3:a0:1e:7f:e2:e7:f7:c3:94:7f:61:48:12:13:aa:c3:78:a6:89:8a:80:e1:45:02:b3:2c:17:d6:b4:1d:d8:c6:5a:e4:89:a4:d8:53:a3:16:48:cf:5d:cf:73:a5:92:fc:cf:d7:d1:0c:02:39:f9:ec:1b:62:b9:bc:7e:b8
[P] WPS Manufacturer: Technicolor
[P] WPS Model Name: MediaAccess TG
[P] WPS Model Number: 799vn v2
[P] Access Point Serial Number: 1528CS3J9
[+] Received M1 message
[P] R-Nonce: ad:d9:9e:37:11:c4:74:cb:67:b5:f7:59:f1:9b:be:8b
[P] PKR: 39:24:c4:c1:dd:94:d8:d4:8d:2b:e5:e8:2b:ef:9b:a7:0d:35:71:80:bc:b9:53:93:9f:23:2e:e8:aa:69:7a:c1:8d:e1:0f:b0:3e:6f:49:1b:5a:99:9c:30:30:d6:08:ae:50:e0:fa:f7:8c:2d:68:74:73:3e:f5:18:95:9e:4f:6e:04:62:7e:89:aa:d9:9c:7d:a4:72:86:23:8e:80:d9:48:70:c8:53:e6:75:fe:50:4d:44:5b:81:e4:62:16:05:59:33:3f:c4:38:a9:8e:8c:7f:ac:af:77:17:db:3d:25:5e:c8:6f:05:bd:dd:4f:46:b1:0c:dd:5b:2b:e0:1c:95:0e:b7:35:a0:47:81:b6:a7:47:43:ad:d1:dd:06:a2:c0:91:1c:34:57:ec:3c:d6:6e:fb:9d:2e:37:aa:59:95:50:31:3a:bc:b0:de:49:d4:19:f1:e1:d6:c5:75:1a:ef:38:4c:84:3d:88:dd:19:fe:69:69:ea:9b:75:b9:0a:60:bc:bc
[P] AuthKey: 6e:96:d5:ad:18:06:ed:ea:f0:01:26:9e:9e:a4:cc:aa:99:29:04:b1:7b:e1:cb:c8:20:00:60:03:51:1f:5d:90
[+] Sending M2 message
[+] Received WSC NACK (reason: 0x000F)
[+] Sending WSC NACK
[!] WPS transaction failed (code: 0x04), re-trying last pin
[+] Trying pin "12345670"
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[P] E-Nonce: 0d:fd:0a:27:10:a5:9a:13:a7:94:e2:e0:0b:88:2c:84
[P] PKE: 38:ee:ec:42:0d:32:e9:5e:a7:60:15:59:58:16:3f:31:11:72:77:cb:7e:09:39:5f:58:c0:d1:85:f4:06:b4:d1:1e:fa:b3:c9:f9:2b:2f:cd:33:a7:34:57:1e:32:ab:ee:d6:ce:14:c4:fb:e6:f1:44:d2:ce:c3:9a:5c:62:b4:4b:55:4b:f3:87:3c:b0:5b:fc:ac:9e:96:62:9b:a1:8e:d5:ca:34:76:23:75:0e:e9:bc:69:78:e5:c8:0b:5e:4a:94:ca:5e:f5:9d:8a:15:9d:c1:95:5e:bb:84:43:c0:01:ec:a8:99:cd:f7:b9:90:a3:c1:01:e3:7b:83:3e:68:3c:69:2c:7f:94:6c:14:f2:e1:e7:61:f7:79:9f:ba:1a:10:a3:28:30:c3:cc:fa:50:60:0e:17:c0:be:54:d6:d0:3c:3d:b5:4d:c9:da:f5:76:35:5b:16:a7:de:d6:69:2b:d4:22:c7:e4:7b:d8:d5:35:71:22:d8:df:b9:6f:30:38:0d:4e
[P] WPS Manufacturer: Technicolor
[P] WPS Model Name: MediaAccess TG
[P] WPS Model Number: 799vn v2
[P] Access Point Serial Number: 1528CS3J9
[+] Received M1 message
[P] R-Nonce: 77:94:07:ba:68:f9:8f:15:19:3a:7b:4e:8f:17:df:0c
[P] PKR: de:ec:5a:66:46:75:1c:b0:b2:e7:c9:47:a0:c3:b4:65:35:e4:23:63:d7:b4:e8:f0:45:18:e1:53:a4:84:fa:13:d5:6a:e1:df:a7:a0:79:3b:34:f5:f4:49:0b:1b:85:ed:f3:3a:2d:07:42:37:39:1e:b7:26:de:87:a5:80:6b:8a:2e:0f:c4:4b:c7:e9:f5:75:13:c9:38:45:dd:01:c7:0b:0d:2c:6d:80:ba:99:99:ff:d4:d4:5e:a2:d1:9c:15:32:71:cf:a9:cb:2e:9d:28:b9:a5:d6:a7:93:b2:11:fc:d2:55:ff:38:96:da:c9:4f:5a:5c:88:5e:03:f5:4a:c8:bc:82:41:18:f2:c9:25:b6:4f:e3:e6:69:ec:11:d4:64:16:9f:05:5c:2e:4c:d5:ab:ef:04:69:6f:94:e6:a6:ff:a2:53:c5:d9:84:7b:b5:6a:a9:c4:ac:54:b3:29:30:bc:1d:84:3c:9e:c0:38:b5:d0:04:f8:8b:51:59:61:50:8a:6d
[P] AuthKey: 36:bf:91:71:95:26:fb:17:5c:2f:2f:3f:3b:99:f1:f2:75:7a:d8:e1:5a:82:89:a4:48:9e:ab:18:6a:99:5d:ec
[+] Sending M2 message
[+] Received WSC NACK (reason: 0x000F)
[+] Sending WSC NACK
[!] WPS transaction failed (code: 0x04), re-trying last pin
[+] Trying pin "12345670"
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[P] E-Nonce: 7c:ed:b4:27:cd:32:24:7f:75:6c:f5:5e:30:c3:3e:ff
[P] PKE: 1d:0e:d8:8f:0d:85:03:da:05:04:60:84:27:7e:72:bb:64:42:a3:c1:fe:4b:b6:9d:7d:7c:db:dd:ff:9f:f4:37:71:70:56:18:a6:9e:22:4b:ce:b7:03:4c:83:86:6d:dc:12:57:b1:85:dc:f0:58:15:83:eb:3d:bf:27:57:7e:de:52:a2:4f:64:98:55:64:32:2d:85:72:ec:db:7f:ec:4b:d3:9b:cf:11:a3:01:8a:de:e0:eb:e3:0a:15:da:f1:e8:2f:82:bf:af:b2:21:92:32:4e:8e:d8:6b:68:93:d1:42:92:cc:77:43:57:5c:98:d2:8d:9f:ef:e1:64:7e:04:ce:06:bc:a4:d8:fe:9f:b3:f9:55:94:b8:f9:2c:fb:71:60:b7:c5:d5:61:29:97:94:8a:e5:dd:21:35:9a:f9:8c:1c:b6:72:42:3c:2a:07:3b:ab:c4:4a:b0:15:c3:2b:64:a0:e7:00:c9:21:f9:19:68:5b:99:6a:1f:94:53:51:2c:4a
[P] WPS Manufacturer: Technicolor
[P] WPS Model Name: MediaAccess TG
[P] WPS Model Number: 799vn v2
[P] Access Point Serial Number: 1528CS3J9
[+] Received M1 message
[P] R-Nonce: a6:b7:59:d1:45:d5:9a:27:a1:b6:5a:94:11:cd:61:04
[P] PKR: 87:4a:49:55:7a:a4:b9:a2:25:09:73:df:a3:30:9f:2a:24:ed:6b:d8:50:92:dd:25:bb:c8:43:24:ac:3b:07:bf:da:38:a9:dd:91:b9:b9:c7:2d:14:34:17:41:96:d1:d4:d2:93:61:92:03:e6:cf:c8:67:1e:ce:0a:1e:a1:47:37:3c:f2:18:2c:da:0a:92:00:9c:38:f0:d4:89:1b:da:10:19:f6:5a:15:c0:5c:6b:5a:b8:4c:3b:3f:bf:a8:66:96:af:79:5d:61:72:d1:7a:4a:4c:07:e6:91:c3:1a:55:c1:e5:e9:6d:6d:03:94:d4:cc:89:69:1f:8c:e0:f5:62:b7:4c:33:ed:62:1d:1a:c0:60:4c:96:f1:ee:d9:7c:40:2d:0d:81:8c:4c:fd:18:fb:d7:7c:c7:0d:5f:e1:8f:f4:d2:04:49:38:d1:32:63:a1:dc:04:e3:0c:e3:52:f2:0c:c9:5d:42:1a:6b:eb:59:bb:b6:28:30:fb:bd:3b:22:e6:7f
[P] AuthKey: ee:cb:dc:4a:9c:3e:40:0d:cb:cf:bb:e8:8e:3d:98:9b:4c:2e:46:88:ab:8d:19:e1:79:e2:88:62:3b:de:3a:d2
[+] Sending M2 message
[+] Received WSC NACK (reason: 0x000F)
[+] Sending WSC NACK
[!] WPS transaction failed (code: 0x04), re-trying last pin
[+] Trying pin "12345670"
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[P] E-Nonce: 23:c1:d7:0d:5b:31:31:fb:76:01:97:d5:0f:9c:7c:5a
[P] PKE: 27:f6:cb:14:12:24:08:58:b6:dc:01:12:7b:7d:11:c8:f1:65:ec:5e:43:24:79:e6:34:3e:bb:e9:08:ea:0f:90:a9:2c:17:bf:d3:c7:e2:0d:08:c0:ea:63:93:23:4e:94:06:c8:58:57:ce:bf:0d:91:49:a4:79:82:e5:36:ae:dc:36:52:40:1a:82:7d:5e:0c:46:cd:4e:08:9e:ef:86:80:b7:6b:72:3c:66:6e:fe:b3:4d:2a:61:78:47:1e:27:31:77:de:03:32:14:fe:4f:e6:1d:17:6c:d0:e9:7b:b0:32:13:56:ba:f8:47:f9:ef:e9:9d:89:cd:13:31:52:0d:63:44:1f:4a:8e:eb:b5:97:44:a1:f8:34:7c:99:ad:37:b5:b8:b4:c9:6b:0a:57:42:ea:ea:92:94:ab:55:f6:7b:1b:38:de:e7:76:e5:96:85:43:d9:d5:86:fa:5f:5b:cb:b6:41:56:dc:c4:ea:b0:2f:7e:ac:fe:e6:ba:a1:ae:83:2b
[P] WPS Manufacturer: Technicolor
[P] WPS Model Name: MediaAccess TG
[P] WPS Model Number: 799vn v2
[P] Access Point Serial Number: 1528CS3J9
[+] Received M1 message
[P] R-Nonce: 68:5b:ce:35:43:cf:04:3f:d2:a2:20:3b:6f:b0:c4:2f
[P] PKR: 91:53:73:2e:b5:f8:b7:d4:e9:60:d9:c6:a5:70:ec:e2:6d:c0:cf:de:98:c2:8d:ca:46:2c:c0:37:f3:16:3f:5b:17:2e:11:f8:64:1e:28:a5:08:b5:a6:b0:0d:6e:b1:67:35:06:b1:8a:a1:b9:c8:34:be:98:c7:a5:20:b1:09:6e:65:8a:20:c7:cf:6d:c9:7f:c3:6c:24:61:10:a6:7a:08:0f:23:dc:77:f5:39:64:0e:97:2b:06:6a:a6:02:0c:19:ef:5d:86:61:e9:0e:d8:2c:da:cf:f0:d0:cf:a7:c5:e6:73:e2:ad:57:82:d3:2a:4a:9f:5d:40:ba:d6:aa:1f:aa:fe:d7:35:ed:fc:08:21:5d:eb:0d:4c:07:35:ba:ef:74:fd:6f:72:b2:c5:76:a8:1c:ac:6b:20:2b:5f:12:74:20:7b:c3:f6:6f:9c:21:35:2d:53:ac:a1:e9:3c:ed:d9:8b:f6:83:41:dc:59:c9:56:92:af:a9:2b:39:54:bd:6e:e3
[P] AuthKey: 3a:4b:39:d4:08:85:5b:29:ed:07:37:9d:f6:b1:8b:6d:7a:a2:54:0a:e6:65:68:7c:1e:4b:46:f6:a6:d3:a5:6e
[+] Sending M2 message
[+] Received WSC NACK (reason: 0x000F)
[+] Sending WSC NACK
[!] WPS transaction failed (code: 0x04), re-trying last pin
[+] Trying pin "12345670"
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[P] E-Nonce: 65:27:70:cb:6f:38:65:f2:5a:37:f8:1b:fa:9a:23:bb
[P] PKE: 92:5c:6b:c0:dc:0f:c8:2a:35:73:24:cd:dc:8e:3b:1b:26:cb:26:be:fb:e0:e3:bb:ba:88:d6:04:5b:61:03:66:3b:9b:e8:73:6b:d7:1d:4a:d4:76:67:5a:a8:0e:e8:f5:e8:4e:3e:c8:be:d9:b7:bd:77:7d:a7:43:5f:0e:99:25:14:ee:99:6d:15:b1:7c:f0:c6:6d:79:9d:2b:72:78:93:a9:68:c3:14:ab:67:f7:c3:82:5a:15:1c:a9:83:b6:ef:b9:ea:d1:38:fe:1e:a3:5c:05:80:cd:9e:1a:2d:17:86:26:2a:0c:f6:3e:70:2c:da:b6:f6:e6:da:bb:95:c1:c8:b7:b4:52:13:10:b3:74:fb:e3:7b:05:a6:90:99:fd:df:bf:f2:48:dd:bb:90:bb:ec:8b:cd:ac:31:04:a5:3c:57:b7:a5:9d:36:53:01:97:f1:95:37:73:1f:3d:f8:19:cf:6a:ec:bf:89:1e:a6:d2:ec:71:3c:d5:94:55:b9:65:0a
[P] WPS Manufacturer: Technicolor
[P] WPS Model Name: MediaAccess TG
[P] WPS Model Number: 799vn v2
[P] Access Point Serial Number: 1528CS3J9
[+] Received M1 message
[P] R-Nonce: 5a:6f:8b:dc:9a:3f:9a:1f:3f:23:d1:96:3c:b6:9b:3e
[P] PKR: 2d:4d:b6:84:95:77:37:f0:6d:05:fb:4d:56:aa:52:96:ac:41:18:a4:e3:83:8f:2d:2c:3a:b1:85:a1:be:5b:da:d8:f7:19:5f:2c:a1:a3:1d:50:eb:5b:7c:cc:77:39:65:2b:ba:c6:ea:b2:65:cd:d2:c2:f2:3e:ed:12:7b:77:91:15:22:f5:80:d7:4b:bc:48:54:5b:92:d3:b5:f2:f5:76:fa:b2:0a:ea:04:64:c8:d3:74:e7:75:a9:9a:27:e4:56:00:b1:8c:38:69:28:9f:8c:78:9b:4d:e2:b1:57:19:53:9c:fd:9f:4b:59:57:3d:e1:c4:8c:88:d1:07:b4:f3:88:ed:4a:95:f9:e9:e8:f2:17:ea:51:f3:79:a5:42:f7:7f:30:fd:96:73:39:93:db:c0:b3:ce:9a:ba:bf:b8:9d:06:1a:75:2e:28:cf:7f:e8:bd:ca:97:02:9c:4a:1d:c2:5a:53:e9:18:25:d2:58:0c:2a:c1:e9:ef:0f:8d:09:d9:6b
[P] AuthKey: 65:d2:86:3c:25:a5:1b:be:4a:43:4b:e1:f4:34:b2:15:98:76:9a:e3:93:ec:87:d3:76:7f:7e:96:a8:0c:4a:5f
[+] Sending M2 message
[+] Received WSC NACK (reason: 0x000F)
[+] Sending WSC NACK
[!] WPS transaction failed (code: 0x04), re-trying last pin
[+] Nothing done, nothing to save.
[+] 0.00% complete. Elapsed time: 0d0h0m12s.
[+] Trying pin "12345670"
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[P] E-Nonce: 85:5a:27:61:c4:71:48:7a:e3:af:bb:04:bf:73:35:ea
[P] PKE: 26:61:5e:16:66:6d:a8:de:cd:76:d0:d9:fc:23:6b:e1:fd:cd:0e:20:4d:80:06:1c:6f:f1:47:7a:08:65:0f:db:fb:6f:83:d4:eb:e5:18:77:f4:f3:a2:6b:f8:99:f6:a5:06:27:85:83:e2:52:72:df:7f:51:b9:5c:33:7a:aa:85:2b:e7:ca:0c:47:5b:0a:68:67:21:30:63:22:5a:7e:cb:20:be:d7:f6:e1:29:6b:02:97:a8:49:34:da:81:b2:2b:0c:83:f4:52:13:7f:da:dd:14:bc:a9:7c:62:34:be:74:18:a3:cd:0d:89:f3:91:0f:43:20:2b:33:2a:ca:31:07:11:14:b2:07:ab:fd:a6:de:78:9d:29:62:4d:12:13:0a:08:cf:18:05:b5:9d:f8:40:86:dc:cd:7a:74:7d:a0:8c:8e:6f:63:c4:ea:1b:08:08:83:3d:f3:cf:2a:6e:96:b4:df:78:59:cc:d5:2e:6d:a6:d4:72:f2:d5:8e:0b:8e:50
[P] WPS Manufacturer: Technicolor
[P] WPS Model Name: MediaAccess TG
[P] WPS Model Number: 799vn v2
[P] Access Point Serial Number: 1528CS3J9
[+] Received M1 message
[P] R-Nonce: c5:c2:28:85:d3:a9:ab:69:a0:db:84:ec:38:e8:41:f6
[P] PKR: b8:fa:64:26:13:37:5a:51:bc:03:b9:ae:41:8c:58:ff:dc:d9:a2:3b:23:02:eb:2b:73:25:93:eb:77:98:6f:f5:c2:2e:a8:f5:9a:48:02:68:32:c5:e0:1b:b5:b6:e5:a7:44:19:69:1a:21:e4:15:67:b8:aa:7e:89:1d:f9:9e:fe:9d:37:28:12:82:bc:a9:99:fd:06:11:17:9f:2b:4b:a6:5d:c9:ce:85:0c:38:d6:ca:bb:a9:3f:8f:88:1f:27:c8:be:7a:a9:40:43:d5:87:81:5d:55:f2:32:ca:7d:aa:77:2e:28:a5:94:00:21:77:1a:eb:73:83:4a:61:8a:56:53:ca:f7:17:83:2e:b6:78:d2:73:ce:c3:b3:32:5e:de:51:3c:f6:12:98:71:87:59:f3:95:23:ca:65:21:31:4b:39:71:bc:89:fa:ae:41:15:ec:f2:1b:5e:9a:52:31:5d:1c:18:98:f4:2c:69:a8:b0:56:9b:00:0a:72:43:93:fe:70
[P] AuthKey: d2:56:80:1d:53:bf:ce:14:11:df:f4:4b:c7:37:a5:3b:a0:9b:2f:3c:8b:bb:a7:87:6d:30:e0:cb:32:62:28:d8
[+] Sending M2 message
[+] Received WSC NACK (reason: 0x000F)
[+] Sending WSC NACK
[!] WPS transaction failed (code: 0x04), re-trying last pin
[+] Trying pin "12345670"
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[P] E-Nonce: 02:6b:ac:80:62:e4:ea:6d:90:30:82:c3:91:69:cf:b9
[P] PKE: 2a:97:0e:6f:c6:97:93:73:e0:1b:6e:53:78:9e:65:d9:17:03:3f:29:94:7d:f9:cd:71:83:0f:97:61:37:a0:94:7b:ff:0a:11:d3:af:fb:9c:31:a8:96:ce:d1:6b:a6:c7:61:6a:b9:a6:47:26:cb:a8:fd:1e:fa:be:de:75:bd:26:07:8e:e3:95:31:6f:5c:0c:cf:14:58:24:47:e2:d3:53:49:93:9d:68:92:58:2a:a9:20:b3:58:56:ad:57:d5:d1:63:85:8b:22:66:e4:31:08:c7:94:2d:17:d4:84:46:91:fa:0b:f4:76:12:b3:b8:19:a8:d0:4d:9a:23:52:44:e9:88:57:04:55:fc:bd:b5:50:de:c8:29:5c:66:41:21:88:2c:a0:0a:6f:d6:19:24:7c:04:63:67:3d:7c:0c:9c:e9:74:01:3c:db:6c:7a:d6:d0:3a:d4:cf:90:23:19:7d:4e:2e:9a:aa:9e:14:e3:3b:3e:59:34:4b:4b:af:af:2a:6b
[P] WPS Manufacturer: Technicolor
[P] WPS Model Name: MediaAccess TG
[P] WPS Model Number: 799vn v2
[P] Access Point Serial Number: 1528CS3J9
[+] Received M1 message
[P] R-Nonce: 1a:af:77:fc:d2:58:92:4a:ba:6f:f3:e9:61:a3:c6:ed
[P] PKR: 53:9c:79:b1:7d:2d:6a:dc:38:59:42:f9:e4:7c:e2:d5:88:2d:dd:b2:2d:b8:17:b1:62:25:39:c4:05:76:04:37:0f:db:07:ca:84:d0:11:1b:3a:88:e6:d4:ba:0f:96:45:6b:76:0e:13:75:5c:5d:11:5d:ab:be:a8:71:54:68:78:a8:c3:6c:6d:ad:17:55:4d:f1:1a:c7:e5:80:3c:c3:da:a3:1a:b0:6f:8e:2e:46:41:54:63:e0:df:ba:f8:5a:93:90:3f:c6:f4:3f:a1:38:cd:73:4e:1b:b7:ab:82:63:5f:47:2c:23:4f:ea:20:ac:bf:c7:7e:f5:45:80:a7:3b:2a:8d:21:34:01:12:0c:fe:94:e9:57:55:3f:9a:f0:66:30:d3:a8:e1:54:5e:cd:c6:0b:d8:53:64:bb:3c:36:f6:bd:bc:c1:0c:a8:cd:03:7f:f2:bf:63:2e:8b:8c:6a:64:0b:5d:e1:12:77:d5:aa:4d:b3:c3:0b:a9:4e:6d:b2:b2:da
[P] AuthKey: e3:5d:1e:84:d0:0d:c4:98:bc:23:d1:cb:32:5d:4e:8e:e6:e1:39:86:a0:14:48:27:94:23:48:f0:1d:fe:e1:21
[+] Sending M2 message
[+] Received WSC NACK (reason: 0x000F)
[+] Sending WSC NACK
[!] WPS transaction failed (code: 0x04), re-trying last pin
^C
[+] Nothing done, nothing to save.

**Comment by soxrok2212** [comment]
Is WPS pin mode enabled in the web UI?

**Comment by soxrok2212** [comment]
The admin panel on the router.

**Comment by Ghostfro** [comment]
yes

**Comment by Ghostfro** [comment]
and it shows also on the wash command

**Comment by soxrok2212** [comment]
Also, you're using a very old version of Reaver. Please update to the newest. Try manually specifying the PIN first and see if you recover the key that way.

**Comment by Ghostfro** [comment]
I used every version of reaver got the same problem, even the lastest one ! and my goal is to get the pin of this AP, i dont know it so i cant try it manualy with "-p"

**Comment by soxrok2212** [comment]
This tool is meant to test your own AP that you already know the credentials for. We do not support breaking into other people's networks here.

**Comment by Sayedaghaj** [comment]
> This tool is meant to test your own AP that you already know the credentials for. We do not support breaking into other people's networks here. That being said, you will not be able to supply proper information to even fix an issue if there is one, since you don't own the AP.

FUCK YOU BULLLY 
DICK  @!

**Comment by Sayedaghaj** [comment]
> This tool is meant to test your own AP that you already know the credentials for. We do not support breaking into other people's networks here. That being said, you will not be able to supply proper information to even fix an issue if there is one, since you don't own the AP.

FUCK YOU BULLY
DICK

**Comment by soxrok2212** [comment]
> > This tool is meant to test your own AP that you already know the credentials for. We do not support breaking into other people's networks here. That being said, you will not be able to supply proper information to even fix an issue if there is one, since you don't own the AP.
> 
> FUCK YOU BULLY DICK

I was going to delete this but I hope if you have a future employer(s), they see this and reconsider.
