### ISSUE TITLE
Stuck at 90.90% 

### ISSUE THREAD

**Issue by idanlo** [t6x/reaver-wps-fork-t6x#174]
root@kali:~# reaver -b AA:BB:CC:DD:EE:FF -c 11 --dh-small -N -L -i wlan0mon 

Reaver v1.6.1 WiFi Protected Setup Attack Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>

[?] Restore previous session for 20:76:00:14:A1:90? [n/Y] y
[+] Restored previous session
[+] Waiting for beacon from AA:BB:CC:DD:EE:FFF
[+] Associated with AA:BB:CC:DD:EE:FF (ESSID: neta2)
[+] 90.90% complete @ 2017-10-24 10:12:31 (2 seconds/pin)
[+] 90.90% complete @ 2017-10-24 10:12:40 (1 seconds/pin)
[+] 90.90% complete @ 2017-10-24 10:12:50 (1 seconds/pin)

This just goes on and on.. I've seen online many people have this problem but no solution found yet..

**Comment by rofl0r** [comment]
Reaver v1.6.1 -> too old
use latest git, and use -vv

**Comment by idanlo** [comment]
How do I get the latest git?

**Comment by idanlo** [comment]
After cloning the git I need to do the other setup mentioned in the main page?

**Comment by rofl0r** [comment]
you need to compile it, according to the instructions

**Comment by kcdtv** [comment]
As the thread is invalid and idanlo didn't show up since more than one month this issue is closed.
