### ISSUE TITLE
this version sucks

### ISSUE THREAD

**Issue by SuperUserRoot** [t6x/reaver-wps-fork-t6x#181]
i can crack almost every wireless with the old reaver (1.4)...

but with this one not one!!!
 
there are no m4 msg etc and not one router im attacking gets locked.
so something is wrong here!

**Comment by adde88** [comment]
Do you have any verbose logs from any failed attempts?

**Comment by soxrok2212** [comment]
When you come back with an appropriate issue and documentation we will consider helping you
