### ISSUE TITLE
how can i hack  a hidden network ??

### ISSUE THREAD

**Issue by minanagehsalalma** [t6x/reaver-wps-fork-t6x#183]
when i start reaver on a wps enabled network it Stuck on waiting for beacon

any ideas ??

**Comment by rofl0r** [comment]
if the network is hidden you must pass both essid and bssid

**Comment by kcdtv** [comment]
That os basicaly what you have to do with a hiden network to connect to it: provides it essid.

**Comment by minanagehsalalma** [comment]
With the -e option !!?!??   I will try and tell you

**Comment by kcdtv** [comment]
Yes, with the **-e** (_--essid_) option 
`-e, --essid=<ssid>              ESSID of the target AP`
