### ISSUE TITLE
WARNING: Receive timeout occurred. RTL3070

### ISSUE THREAD

**Issue by vido89** [t6x/reaver-wps-fork-t6x#184]
Im using latest reaver but I keep getting timeout error

```
$ sudo ./reaver -i wlx3c3300200748 -b 04:8D:38:XX:XX:XX -p 72187517 -vv

Reaver v1.6.3 WiFi Protected Setup Attack Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>

[+] Waiting for beacon from 04:8D:38:XX:XX:XX
[+] Switching wlx3c3300200748 to channel 6
[+] Received beacon from 04:8D:38:XX:XX:XX
[+] Vendor: RealtekS
[+] Trying pin "72187517"
[+] Sending authentication request
[!] WARNING: Receive timeout occurred
[+] Sending authentication request
[!] WARNING: Receive timeout occurred
[+] Sending authentication request
[!] WARNING: Receive timeout occurred
[+] Sending authentication request
[!] WARNING: Receive timeout occurred
[+] Sending authentication request
[!] WARNING: Receive timeout occurred
[+] Sending authentication request
```
What could be wrong ? Im in rage, and I placed XX to cover MAC address ?

**Comment by soxrok2212** [comment]
Is your card in monitor mode?

**Comment by vido89** [comment]
Hi @soxrok2212 yes it is, I tried with mon0 also, same deal on three different routers 
```
iwconfig 
enp2s0    no wireless extensions.

lo        no wireless extensions.

vmnet1    no wireless extensions.

mon0      IEEE 802.11bgn  Mode:Monitor  Frequency:2.462 GHz  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          
wlx3c3300200748  IEEE 802.11bgn  Mode:Monitor  Frequency:2.462 GHz  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          
vmnet8    no wireless extensions.
```

**Comment by soxrok2212** [comment]
What is the card?

**Comment by vido89** [comment]
Its Ra Link 3070

**Comment by rofl0r** [comment]
its clear from the log what happens:
authentication packets are sent, but no response is received.
possible reasons:
- injection doesnt work
- AP doesn't receive your packets (too far away/too much congestion)
- AP uses mac filtering

**Comment by soxrok2212** [comment]
Also note that in some cases (very rare), WPS is enabled but not configured and may cause errors. Might also be useful to see if you can associate with aireplay-ng.

**Comment by vido89** [comment]
It seams that does not support injection any more, strange it was working with BT and kali some time a go. I will try backports, do you guys have any sugestion how to roll back drivers to some old version. The drivers are issue.

**Comment by rofl0r** [comment]
what's the version of your kernel (run `uname -a`) ?

**Comment by vido89** [comment]
```
$ uname -a
Linux G31M-ES2L 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vido89** [comment]
I think that this is new feature in rtl3070 drivers for monitor mode, does not support sending packets

**Comment by rofl0r** [comment]
that bug was fixed in kernel 4.5, see https://github.com/sabotage-linux/sabotage/blob/master/KEEP/linux-4.3-ralink-monitor.patch

**Comment by vido89** [comment]
Con you do anything to apply those changes to my kernel or to just wait for it. tnx

**Comment by rofl0r** [comment]
i dont think the LTS distro you use will ever switch to a newer kernel. try booting from a kali live cd, or read up on how to install a newer kernel on ubuntu. good luck

**Comment by vido89** [comment]
I see ok tnx for your help,I wish you happy new year and good helth cheers

**Comment by rofl0r** [comment]
thanks, same to you.

**Comment by rofl0r** [comment]
@vido89 could you please also close your double-post https://forum.aircrack-ng.org/index.php/topic,1719.msg5768.html#msg5768 and point at the resolution here? thanks.

**Comment by vido89** [comment]
Sure :)

**Comment by vido89** [comment]
Something is not right with rtl3070, I tried it on kali but reaver isnt working, here is [reaver.log](https://github.com/t6x/reaver-wps-fork-t6x/files/1601538/reaver.log)
Also I have OpenWrt/LEDE box with ar9285 and it works just fine, its same distance to router, the drivers for rtl 3070 are not correct I assume ?

**Comment by vido89** [comment]
And here is log from LEDE box 
[AR9285.log](https://github.com/t6x/reaver-wps-fork-t6x/files/1601592/AR9285.log)

**Comment by rofl0r** [comment]
you need -N

**Comment by vido89** [comment]
Yup that worked, tnx a lot

**Comment by ligmaDX800** [comment]
What about this one, output is same except that different arguments were used.
@rofl0r

**Comment by rofl0r** [comment]
please open your own, new issue, after you tried everything pointed out here and in the wiki article https://github.com/t6x/reaver-wps-fork-t6x/wiki/Troubleshooting
