### ISSUE TITLE
no pcap

### ISSUE THREAD

**Issue by gmurman770** [t6x/reaver-wps-fork-t6x#186]
Im new to GitHub and linux, but i think that something missed here ?

~/reaver-wps-fork-t6x/src# ./configure 
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
**checking for pcap_open_live in -lpcap... no
error: pcap library not found!**

~/reaver-wps-fork-t6x/src# make
cp lwe/wireless.21.h lwe/wireless.h
cc -DCONF_DIR='""'  -Wno-unused-variable -Wno-unused-function -Wno-pointer-sign -Ilibwps -I. -Ilwe -DCONFIG_IPV6   -c -o argsparser.o argsparser.c
In file included from globule.h:37:0,
                 from argsparser.c:37:
defs.h:43:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~
compilation terminated.
<builtin>: recipe for target 'argsparser.o' failed
make: *** [argsparser.o] Error 1

**Comment by soxrok2212** [comment]
`sudo apt-get install libpcap-dev libel-dev`
