### ISSUE TITLE
Instrallation Issue

### ISSUE THREAD

**Issue by naflan121** [t6x/reaver-wps-fork-t6x#20]
I follow up the instruction to install, Everything Was fine but still reaver is not updated, Any checklists?

**Comment by soxrok2212** [comment]
Which operating system are you using?

**Comment by naflan121** [comment]
im using kali linux

**Comment by beddj** [comment]
Is this for the installation? I'm good. It didn't work at first but I
restarted the terminal and it worked. But if this is for the netgear router
I'm using Kali Linux

**Comment by soxrok2212** [comment]
Navigate to /usr/local/bin and remove pixiewps, reaver, and wash if it is in there. The easiest way to install is just through apt. First, just to be sure, remove any existing versions: apt-get remove reaver and apt-get remove pixiewps.

Then, apt-get install reaver and it should add pixiewps in automatically as well. If it doesnt. apt-get install pixiewps.

Close terminal and reopen then everything should work fine and it will automatically update every time you run apt-get update && apt-get upgrade

**Comment by naflan121** [comment]
oki thanks ill try and leave the feedbacks
