### ISSUE TITLE
not empty Vendor field in wash

### ISSUE THREAD

**Issue by wpa2** [t6x/reaver-wps-fork-t6x#203]
Is it possible to output "Unknown" or something similar in the "Vendor" field if the manufacturer is unknown? To simplify the parsing of a text file obtained with tee.

**Comment by rofl0r** [comment]
the default output of wash is not meant to be parseable, and is subject to frequent changes (i.e. there is no guarantee it won't change).
we especially added the -j json output for scripters and parsers.
