### ISSUE TITLE
sanitize_string()  is incompatible with Chinese characters.

### ISSUE THREAD

**Issue by ChunshengZhao** [t6x/reaver-wps-fork-t6x#205]
root@kali:~/test# ./chinese_ssid
Hex:
0x33,0x36,0x30,0xe8,0xa1,0x8c,0xe8,0xbd,0xa6,0xe8,0xae,0xb0,0xe5,0xbd,0x95,0xe4,0xbb,0xaa,0x2d,0x31,0x31,0x32,0x32
Normal:
360行车记录仪-1122
Abnormal:
360\\xe8\\xa1\\x8c\\xe8\\xbd\\xa6\\xe8\\xae\\xb0\\xe5\\xbd\\x95\\xe4\\xbb\\xaa-1122

[chinese_ssid.zip](https://github.com/t6x/reaver-wps-fork-t6x/files/1762368/chinese_ssid.zip)

**Comment by rofl0r** [comment]
well, we have a dilemma here. the sanitize_string() function was added so an attacker cannot inject terminal control codes by abusing the essid field to mess up your terminal or worse, write arbitrary files or execute code: https://www.proteansec.com/linux/blast-past-executing-code-terminal-emulators-via-escape-sequences/

a thinkable solution to get both security and chinese characters could be to check if the essid is valid UTF-8. but then how can i know if the terminal actually displays UTF-8 or ASCII.

this is a hard problem, and i went for an easy fix.

if you have better ideas let me know.

**Comment by kcdtv** [comment]
>  how can i know if the terminal actually displays UTF-8 or ASCII.

Isn't the "echoed" value of `$LANG` enough? 


> if you have better ideas let me know.


In the worst case we could add a tag in wash to enable special characters and we warn the user in the option description that it might be risky.  That is not the best but does not require too much effort and seems correct as a security policy: User can take risk if he wants, he is warned and this is not the default behavior

**Comment by rofl0r** [comment]
>>    how can i know if the terminal actually displays UTF-8 or ASCII.

> Excuseme if that is stupid... smiley_cat Isn't the "echoed" value of $LANG enough?

not really. in my case LANG is not even set at all. the behaviour can be affected from a number of variables: 1) environment variables 2) default locale 3) libc 4) shell 5) terminal

this is a very non-trivial topic, and i have so far successfully avoided to dive deep into it.

> In the worst case we could add a tag in wash

you mean yet another command line option ? `:-p`

**Comment by kcdtv** [comment]
Yes, I mean another option... As we eliminated -o option there is at least one letter left... "o" like "Original bad essid" :smiley_cat: as it is well known that ssid should use no space or special character, just basic latin alphabet and numbers. But if you/me/somebody finds a nicer way, for sure I am all hear.

**Comment by rofl0r** [comment]
yeah, let's first hear if @ChunshengZhao has some ideas, and if he insists having the chinese letters in his terminal.

btw i'm not a big fan of option letter recycling, at least not so quick after they've been removed. it's better if some time passes so ppl that used `-o` will notice it's no longer there... rather than doing a completely different thing without them noticing.

**Comment by ChunshengZhao** [comment]
Do not care about the terminal character set, if the correct utf-8 string output, otherwise execute sanitize_string (). Maybe add “-utf8” option? Have a attacker’s code is in the utf8 format?

Sorry my english.

**Comment by ChunshengZhao** [comment]
Like this:

root@kali:~/test# ./utf8_ssid 
Normal:
360行车记录仪-1122
Abnormal:
\\x8060\\xe8\\xa1\\x8c\\xe8\\xbd\\xa6\\xe8\\xae\\xb0\\xe5\\xbd\\x95\\xe4\\xbb\\xaa-1122

[utf8_ssid.zip](https://github.com/t6x/reaver-wps-fork-t6x/files/1766970/utf8_ssid.zip)

**Comment by ChunshengZhao** [comment]
![20180301125100](https://user-images.githubusercontent.com/9263377/36827551-4853d48e-1d4f-11e8-8952-d6780e1a97ea.jpg)

[verifyssid.zip](https://github.com/t6x/reaver-wps-fork-t6x/files/1769832/verifyssid.zip)

VerifySSID function (UTF-8 supported):
https://github.com/ChunshengZhao/verifyssid

**Comment by rofl0r** [comment]
nice work. what's your plan with the function ?

**Comment by ChunshengZhao** [comment]
If the development team think the verifyssid() is safe.
easy way :
add "if(verifyssid(s)) return s;" in your sanitize_string().

**Comment by rofl0r** [comment]
i don't know if it is safe. how did you end up with it ? did you read the UTF8 specificiation, or study some validation code in detail ?

**Comment by ChunshengZhao** [comment]
https://en.wikipedia.org/wiki/UTF-8
UTF8 string verification process is correct.
The only hidden danger: a malicious code matching UTF8 encoding rules.
The Reaver does not depend on the SSID, so this is an unnecessary patch.

**Comment by ChunshengZhao** [comment]
@rofl0r 
New requests：
https://github.com/t6x/reaver-wps-fork-t6x/pull/206
