### ISSUE TITLE
reaver Reveice Timeout Occured

### ISSUE THREAD

**Issue by SheesAli** [t6x/reaver-wps-fork-t6x#208]
Please Help me to solve this error. I really hate this error. It was not in 1.6.3

**Comment by soxrok2212** [comment]
I hate when people don’t give information. Other people give information. Please give information.

**Comment by SheesAli** [comment]
When I try to crack WPS it gives this error. 
reaver Reveice Timeout Occurred
I don't know why? I have cracked that same router when I was using kali 2.0... But when I tried to crack the same router using the current version of Reaver it shows this error.

**Comment by soxrok2212** [comment]
My car won’t start. I turn the key and the check engine light turns on but it doesn’t start. What’s wrong?

This is the equivalent to what you’re giving us to work with. What wireless card, driver, OS, version of reaver, etc?

**Comment by SheesAli** [comment]
I am using 1.6.4  latest version of Kali Linux 2018 .1 and the wireless card is Dell Wireless 1702 802.11b|g|n

**Comment by rofl0r** [comment]
try again with 1.6.3. if it doesn't work anymore with that version either, then it's due to changed circumstances. more noise on the channel, different channel, different antenna position, etc etc.

**Comment by rofl0r** [comment]
also read this here https://github.com/t6x/reaver-wps-fork-t6x/wiki/Troubleshooting

**Comment by SheesAli** [comment]
that is my own router I used it to practice.. but now reaver is not working I will try with 1.6.3 and will tell you If its work or not.

**Comment by kcdtv** [comment]
You should have posted the exact command line you used.

> Dell Wireless 1702 802.11b|g|n

This is not useful. What matters is the wifi chipt. You can get it with 

> (sudo) airmon-ng

**Comment by SheesAli** [comment]
Qualcomm Atheros AR9285 Wireless Network Adapter

**Comment by SheesAli** [comment]
I have two laptops One is DELL and other is Lenovo these commands are giving me my wifi password when I am typing this in lenovo but When I am using DELL laptop it is giving an error.

Since I am hacking my own router so I know the pin and the command is

sudo reaver -i wlan0mon -p 29855506 -b bssid-of-the-router -c 3 -vv

My Lenovo laptop is giving me a password when I am typing the same command mentioned above.So there is no problem with reaver I guess. But last year I have hack routers using reaver in my DELL laptop which is I am currently using. Wifi is working perfectly is there any chance to have any fault in my DELL laptop's wireless card because I am using it since day one for Hacking and Deauth Attacks. But wifi is working properly so that's why I am confused

**Comment by amiinebh** [comment]
Check if injection is working , and try to downgrade you kernel version and check

**Comment by SheesAli** [comment]
Injection is working properly.

**Comment by rofl0r** [comment]
maybe use `-N`which is required for some chips. anyway, as one can see the problem is not a mysterious breakage between 1.6.3 and 1.6.4 as originally stated.

**Comment by kcdtv** [comment]
definitely `-N` :wink:

**Comment by SheesAli** [comment]
I guess there is a problem with my wireless card.

**Comment by kcdtv** [comment]
I guess you did not try with `-N` argument.

**Comment by SheesAli** [comment]
Another laptop is giving me password without -N. Then what is the problem with my laptop?

**Comment by rofl0r** [comment]
some chips need it, some don't. as stated before. but it should never hurt to use  the flag, so just add it always. apart from that, we don't have time to help you debug your chip issues. there's the troubleshooting page, and there are USB adapters that work waiting in stores.

**Comment by kcdtv** [comment]
Where is the problem if the option solves the issue? :smiley_cat: Use it, it was desined for that.
