### ISSUE TITLE
can't compile reaver ubuntu 14.04

### ISSUE THREAD

**Issue by sheikhmunawar** [t6x/reaver-wps-fork-t6x#22]
root@Lappi:/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src# make
(cd utils && make)
make[1]: Entering directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/utils'
  CC  base64.c
common.c: In function ‘pingen_zhaochunsheng’:
common.c:597:5: warning: passing argument 1 of ‘snprintf’ makes pointer from integer without a cast [enabled by default]
     snprintf(pin, pin_len, "%08d", (default_pin * 10) + wps_checksum(default_pin));
     ^
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from includes.h:25,
                 from common.c:15:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:61:1: note: expected ‘char * __restrict__’ but argument is of type ‘int’
 __NTH (snprintf (char *__restrict __s, size_t __n,
 ^
common.c: In function ‘pingen_zyxel’:
common.c:614:5: warning: implicit declaration of function ‘wps_pin_checksum’ [-Wimplicit-function-declaration]
     return (pin * 10) + wps_pin_checksum(pin);
     ^
  CC  common.c
  CC  ip_addr.c
  CC  radiotap.c
  CC  trace.c
  CC  uuid.c
  CC  wpa_debug.c
  CC  wpabuf.c
  CC  os_unix.c
  CC  eloop.c
ar crT libutils.a base64.o common.o ip_addr.o radiotap.o trace.o uuid.o wpa_debug.o wpabuf.o os_unix.o eloop.o
make[1]: Leaving directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/utils'
(cd tls && make)
make[1]: Entering directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/tls'
  CC  asn1.c
In file included from bignum.c:21:0:
libtommath.c: In function ‘mp_exptmod’:
libtommath.c:580:9: warning: variable ‘dr’ set but not used [-Wunused-but-set-variable]
     int dr;
         ^
  CC  bignum.c
  CC  pkcs1.c
  CC  pkcs5.c
  CC  pkcs8.c
  CC  rsa.c
  CC  tlsv1_client.c
  CC  tlsv1_client_read.c
  CC  tlsv1_client_write.c
  CC  tlsv1_common.c
  CC  tlsv1_cred.c
  CC  tlsv1_record.c
  CC  tlsv1_server.c
tlsv1_server_read.c: In function ‘tls_process_client_key_exchange_rsa’:
tlsv1_server_read.c:474:9: warning: variable ‘encr_len’ set but not used [-Wunused-but-set-variable]
     u16 encr_len;
         ^
  CC  tlsv1_server_read.c
  CC  tlsv1_server_write.c
  CC  x509v3.c
ar crT libtls.a asn1.o bignum.o pkcs1.o pkcs5.o pkcs8.o rsa.o tlsv1_client.o tlsv1_client_read.o tlsv1_client_write.o tlsv1_common.o tlsv1_cred.o tlsv1_record.o tlsv1_server.o tlsv1_server_read.o tlsv1_server_write.o x509v3.o
make[1]: Leaving directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/tls'
(cd crypto && make)
make[1]: Entering directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/crypto'
  CC  aes-cbc.c
  CC  aes-ctr.c
  CC  aes-eax.c
  CC  aes-encblock.c
  CC  aes-internal.c
  CC  aes-internal-dec.c
  CC  aes-internal-enc.c
  CC  aes-omac1.c
  CC  aes-unwrap.c
  CC  aes-wrap.c
  CC  des-internal.c
  CC  dh_group5.c
  CC  dh_groups.c
  CC  md4-internal.c
  CC  md5.c
md5-internal.c: In function ‘MD5Final’:
md5-internal.c:185:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((u32 *) ctx->in)[14] = ctx->bits[0];
     ^
md5-internal.c:186:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((u32 *) ctx->in)[15] = ctx->bits[1];
     ^
In file included from ../utils/common.h:18:0,
                 from md5-internal.c:17:
md5-internal.c:191:29: warning: argument to ‘sizeof’ in ‘memset’ call is the same expression as the destination; did you mean to dereference it? [-Wsizeof-pointer-memaccess]
     os_memset(ctx, 0, sizeof(ctx)); /* In case it's sensitive */
                             ^
../utils/os.h:413:41: note: in definition of macro ‘os_memset’
 #define os_memset(s, c, n) memset(s, c, n)
                                         ^
  CC  md5-internal.c
  CC  md5-non-fips.c
  CC  milenage.c
  CC  ms_funcs.c
  CC  rc4.c
  CC  sha1.c
  CC  sha1-internal.c
  CC  sha1-pbkdf2.c
  CC  sha1-tlsprf.c
  CC  sha1-tprf.c
  CC  sha256.c
  CC  sha256-internal.c
  CC  crypto_internal.c
  CC  crypto_internal-cipher.c
  CC  crypto_internal-modexp.c
  CC  crypto_internal-rsa.c
  CC  tls_internal.c
  CC  fips_prf_internal.c
ar crT libcrypto.a aes-cbc.o aes-ctr.o aes-eax.o aes-encblock.o aes-internal.o aes-internal-dec.o aes-internal-enc.o aes-omac1.o aes-unwrap.o aes-wrap.o des-internal.o dh_group5.o dh_groups.o md4-internal.o md5.o md5-internal.o md5-non-fips.o milenage.o ms_funcs.o rc4.o sha1.o sha1-internal.o sha1-pbkdf2.o sha1-tlsprf.o sha1-tprf.o sha256.o sha256-internal.o crypto_internal.o crypto_internal-cipher.o crypto_internal-modexp.o crypto_internal-rsa.o tls_internal.o fips_prf_internal.o
make[1]: Leaving directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/crypto'
(cd wps && make)
make[1]: Entering directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/wps'
cc  -I../utils -I ../ wps_attr_build.c -c
cc  -I../utils -I ../ wps_attr_parse.c -c
cc  -I../utils -I ../ wps_attr_process.c -c
cc  -I../utils -I ../ wps.c -c
cc  -I../utils -I ../ wps_common.c -c
cc  -I../utils -I ../ wps_dev_attr.c -c
wps_dev_attr.c: In function ‘wps_process_manufacturer’:
wps_dev_attr.c:200:26: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             printf("%c", (char *) str[pixiecnt]);
                          ^
wps_dev_attr.c:200:13: warning: format ‘%c’ expects argument of type ‘int’, but argument 2 has type ‘char *’ [-Wformat=]
             printf("%c", (char *) str[pixiecnt]);
             ^
wps_dev_attr.c: In function ‘wps_process_model_name’:
wps_dev_attr.c:241:26: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             printf("%c", (char *) str[pixiecnt]);
                          ^
wps_dev_attr.c:241:13: warning: format ‘%c’ expects argument of type ‘int’, but argument 2 has type ‘char *’ [-Wformat=]
             printf("%c", (char *) str[pixiecnt]);
             ^
wps_dev_attr.c: In function ‘wps_process_model_number’:
wps_dev_attr.c:280:26: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             printf("%c", (char *) str[pixiecnt]);
                          ^
wps_dev_attr.c:280:13: warning: format ‘%c’ expects argument of type ‘int’, but argument 2 has type ‘char *’ [-Wformat=]
             printf("%c", (char *) str[pixiecnt]);
             ^
wps_dev_attr.c: In function ‘wps_process_serial_number’:
wps_dev_attr.c:319:26: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             printf("%c", (char *) str[pixiecnt]);
                          ^
wps_dev_attr.c:319:13: warning: format ‘%c’ expects argument of type ‘int’, but argument 2 has type ‘char *’ [-Wformat=]
             printf("%c", (char *) str[pixiecnt]);
             ^
wps_dev_attr.c:344:3: warning: passing argument 1 of ‘pingen_belkin’ makes pointer from integer without a cast [enabled by default]
   printf("[Pin Gen] Pin Generated : %08d\n",pingen_belkin(mac2str(get_bssid(),'\0'), str, str_len, 0));
   ^
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘int’
 int pingen_belkin(char *mac, char *serial, int len_serial, int add); 
     ^
wps_dev_attr.c:344:3: warning: passing argument 2 of ‘pingen_belkin’ discards ‘const’ qualifier from pointer target type [enabled by default]
   printf("[Pin Gen] Pin Generated : %08d\n",pingen_belkin(mac2str(get_bssid(),'\0'), str, str_len, 0));
   ^
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘const u8 *’
 int pingen_belkin(char *mac, char *serial, int len_serial, int add); 
     ^
wps_dev_attr.c:345:3: warning: passing argument 1 of ‘pingen_belkin’ makes pointer from integer without a cast [enabled by default]
   printf("[Pin Gen] Pin Generated (+1): %08d\n",pingen_belkin(mac2str(get_bssid(),'\0'), str, str_len, 1));
   ^
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘int’
 int pingen_belkin(char *mac, char *serial, int len_serial, int add); 
     ^
wps_dev_attr.c:345:3: warning: passing argument 2 of ‘pingen_belkin’ discards ‘const’ qualifier from pointer target type [enabled by default]
   printf("[Pin Gen] Pin Generated (+1): %08d\n",pingen_belkin(mac2str(get_bssid(),'\0'), str, str_len, 1));
   ^
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘const u8 *’
 int pingen_belkin(char *mac, char *serial, int len_serial, int add); 
     ^
wps_dev_attr.c:346:3: warning: passing argument 1 of ‘pingen_belkin’ makes pointer from integer without a cast [enabled by default]
   printf("[Pin Gen] Pin Generated (-1): %08d\n\n",pingen_belkin(mac2str(get_bssid(),'\0'), str, str_len, -1));
   ^
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘int’
 int pingen_belkin(char *mac, char *serial, int len_serial, int add); 
     ^
wps_dev_attr.c:346:3: warning: passing argument 2 of ‘pingen_belkin’ discards ‘const’ qualifier from pointer target type [enabled by default]
   printf("[Pin Gen] Pin Generated (-1): %08d\n\n",pingen_belkin(mac2str(get_bssid(),'\0'), str, str_len, -1));
   ^
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘const u8 *’
 int pingen_belkin(char *mac, char *serial, int len_serial, int add); 
     ^
wps_dev_attr.c:355:3: warning: passing argument 1 of ‘pingen_dlink’ makes pointer from integer without a cast [enabled by default]
   printf("[Pin Gen] Pin Generated : %08d\n",pingen_dlink(mac2str(get_bssid(),'\0'), 0));
   ^
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:448:5: note: expected ‘char *’ but argument is of type ‘int’
 int pingen_dlink(char *mac, int add);        
     ^
wps_dev_attr.c:356:3: warning: passing argument 1 of ‘pingen_dlink’ makes pointer from integer without a cast [enabled by default]
   printf("[Pin Gen] Pin Generated (+1): %08d\n",pingen_dlink(mac2str(get_bssid(),'\0'), 1));
   ^
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:448:5: note: expected ‘char *’ but argument is of type ‘int’
 int pingen_dlink(char *mac, int add);        
     ^
wps_dev_attr.c:357:3: warning: passing argument 1 of ‘pingen_dlink’ makes pointer from integer without a cast [enabled by default]
   printf("[Pin Gen] Pin Generated (-1): %08d\n\n",pingen_dlink(mac2str(get_bssid(),'\0'), -1));
   ^
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:448:5: note: expected ‘char *’ but argument is of type ‘int’
 int pingen_dlink(char *mac, int add);        
     ^
cc  -I../utils -I ../ wps_enrollee.c -c
cc  -I../utils -I ../ wps_registrar.c -c
wps_registrar.c: In function ‘wps_build_m4’:
wps_registrar.c:1499:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ [-Wformat=]
     wpa_printf(MSG_DEBUG, "WPS: Dev Password Len: %d", wps->dev_password_len);
     ^
cc  -I../utils -I ../ wps_ufd.c -c
make[1]: Leaving directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/wps'
(cd lwe && make BUILD_STATIC=y libiw.a)
make[1]: Entering directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/lwe'
cp wireless.21.h wireless.h
gcc -Os -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wpointer-arith -Wcast-qual -Winline -I. -MMD     -fPIC -c -o iwlib.so iwlib.c
iwlib.c: In function ‘iw_enum_devices’:
iwlib.c:254:14: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
         fgets(buff, sizeof(buff), fh);
              ^
iwlib.c:255:14: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
         fgets(buff, sizeof(buff), fh);
              ^
iwlib.c: In function ‘iw_get_kernel_we_version’:
iwlib.c:337:10: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(buff, sizeof(buff), fh);
          ^
iwlib.c:353:10: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(buff, sizeof(buff), fh);
          ^
rm -f libiw.a
ar cru libiw.a iwlib.so
ranlib libiw.a
make[1]: Leaving directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/lwe'
(cd libwps && make)
make[1]: Entering directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/libwps'
gcc -Wall libwps.c -c
libwps.c: In function ‘parse_wps_parameters’:
libwps.c:29:12: warning: variable ‘data_len’ set but not used [-Wunused-but-set-variable]
     size_t data_len = 0, offset = 0;
            ^
make[1]: Leaving directory `/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src/libwps'
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 globule.c -c 
globule.c: In function ‘set_p1_index’:
globule.c:110:9: warning: implicit declaration of function ‘cprintf’ [-Wimplicit-function-declaration]
         cprintf(VERBOSE,"[+] p1_index set to %i\n",index);
         ^
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps argsparser.c -c
argsparser.c: In function ‘process_arguments’:
argsparser.c:97:17: warning: implicit declaration of function ‘set_op_gen_pin’ [-Wimplicit-function-declaration]
                 set_op_gen_pin(atoi(optarg));
                 ^
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 init.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 misc.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps sql.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 builder.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 crc.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps 80211.c -c
80211.c: In function ‘read_ap_beacon’:
80211.c:76:12: warning: variable ‘tag_offset’ set but not used [-Wunused-but-set-variable]
     size_t tag_offset = 0;
            ^
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 iface.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps wpsmon.c *.o libwps/*.o wps/*.o tls/bignum.o tls/libtls.a utils/libutils.a crypto/libcrypto.a lwe/libiw.a -ldl -lm -lpcap -lsqlite3  -o wash
wpsmon.c: In function ‘parse_wps_settings’:
wpsmon.c:427:7: warning: pointer targets in passing argument 2 of ‘strcat’ differ in signedness [-Wpointer-sign]
       strcat(cmd_chipset, mac2str(get_bssid(),':'));
       ^
In file included from /usr/include/features.h:374:0,
                 from /usr/include/ctype.h:25,
                 from /usr/include/getopt.h:33,
                 from wpsmon.h:37,
                 from wpsmon.c:34:
/usr/include/x86_64-linux-gnu/bits/string3.h:140:1: note: expected ‘const char * __restrict__’ but argument is of type ‘unsigned char *’
 __NTH (strcat (char *__restrict __dest, const char *__restrict __src))
 ^
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps sigint.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 sigalrm.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 keys.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 pins.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 send.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps exchange.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps session.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps cracker.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps wpscrack.c *.o libwps/*.o wps/*.o tls/bignum.o tls/libtls.a utils/libutils.a crypto/libcrypto.a lwe/libiw.a -ldl -lm -lpcap -lsqlite3  -o reaver
wpscrack.c: In function ‘main’:
wpscrack.c:40:33: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
     int ret_val = EXIT_FAILURE, r = 0;
                                 ^
root@Lappi:/home/sheikh/Desktop/temp/reaver-wps-fork-t6x/src#

**Comment by soxrok2212** [comment]
You need to run ./configure, then make, then make install.

**Comment by ifytbairz** [comment]
hello soxrok2212,

i have this same issue however I am following the readme exactly. i have the prerequisites, i run ./configure, make but make always fails compiling wpscrack. 

please advise. running fresh linux mint 17.2 64bit

**Comment by tomasjarolim** [comment]
edit wpscrack.c file and remove variable

- on line 38 was something like 
`int ret_val = EXIT_FAILURE, r=...;`
->
`int ret_val = EXIT_FAILURE;`

- on line 118 starting a condition on few lines
`/* Run user-supplied command */`
->
remove all condition

I'm not sure what is user-supplied command, but it work for me
