### ISSUE TITLE
time erorr with my Laptop network card

### ISSUE THREAD

**Issue by newdie484** [t6x/reaver-wps-fork-t6x#231]
http://s8.picofile.com/file/8323493150/Selection_048.png
http://s8.picofile.com/file/8323493176/Selection_047.png 
how to fix that????

**Comment by kcdtv** [comment]
There is not a single concrete element in your "issue". 
Posting two pictures and asking "how to fix pliz" is **not** redacting an issue. 
 - What is your Pa model and wifi chipset?
 - Is the WPS properly enabled with a PIN correctly configured? 
 - What is the model of the wifi chip you are using to perform the tests? 
 - In which distribution with which kernel? 
 - What is the level of PWR and RXQ of the target (check in airodump-ng)?
 - etc. etc.  
And please, do **not** use a crappy external http website to post pictures, use the markdown option to insert code. Debugging is done with stdouts, do **not** use screenshots unless it is to show something that is "graphical only" and  not happening in your shell.

**Comment by newdie484** [comment]
http://s9.picofile.com/file/8323565792/Selection_055.png
http://s9.picofile.com/file/8323565818/Selection_054.png
http://s8.picofile.com/file/8323565826/Selection_053.png
but not fix again

**Comment by binarymaster** [comment]
Why you use `-A` option? Did you ran aireplay-ng to associate with the network?

**Comment by newdie484** [comment]
i just see in one site to fix that but i use with out -A but not correct

**Comment by newdie484** [comment]
http://s9.picofile.com/file/8323625992/Selection_059.png
http://s8.picofile.com/file/8323626000/Selection_060.png
i have this error again when i use code site https://github.com/t6x/reaver-wps-fork-t6x/wiki/Troubleshooting

**Comment by kcdtv** [comment]
we cannot debugg something like that... you are attacking different PA, we still don't have the basic information required. And it is very annoying to check every pictures on an external server... Use markdown or do click on "selecting them"

**Comment by soxrok2212** [comment]
Closing because there has been no response in 3 weeks
