### ISSUE TITLE
is wpacrack.c supposed to fail ?

### ISSUE THREAD

**Issue by ifytbairz** [t6x/reaver-wps-fork-t6x#24]
I'm trying to compile this code, during 'make' i always get this error:

gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps wpscrack.c *.o libwps/*.o wps/*.o tls/bignum.o tls/libtls.a utils/libutils.a crypto/libcrypto.a lwe/libiw.a -ldl -lm -lpcap -lsqlite3  -o reaver
wpscrack.c: In function ‘main’:
wpscrack.c:40:33: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
     int ret_val = EXIT_FAILURE, r = 0;
                                 ^

**Comment by chrisonline909** [comment]
hey guys im getting the same error.. any help would be appreciated 
thank you!

**Comment by kcdtv** [comment]
where do you see an "error"? This is a "warning". Your variable is set but not used. That's not a problem. if you can compile and install = don't worry be happy

**Comment by chrisonline909** [comment]
your right it was not an error, everythings works great! thanks

**Comment by tomasjarolim** [comment]
when still cannot make,
edit wpscrack.c file and remove variable

- on line 38 was something like 
`int ret_val = EXIT_FAILURE, r=...;`
->
`int ret_val = EXIT_FAILURE;`

- on line 118 starting a condition on few lines
`/* Run user-supplied command */`
->
remove all condition

I'm not sure what is user-supplied command, but it work for me
