### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Chessy1991** [t6x/reaver-wps-fork-t6x#263]
![screenshot from 2018-10-10 03-21-13](https://user-images.githubusercontent.com/42880590/46707740-99300d00-cc3b-11e8-959f-d92aa819b7c8.png)
 that's the case, sorry but being noob is frustrating .. till i learn !

**Comment by adde88** [comment]
Looks like a permission issue with a file.
Btw, there's no need to use sudo when you're already root user.
Tru "chmod +x install.sh" inside the same folder.

This issue shouldn't happen if you simply used git to clone the repo.
Did you download the repo as a zip file?

**Comment by Chessy1991** [comment]
i don't recall getting the repo by git clone or as zip... but will give ur solution a try and comment for you! ,Thanks btw!

**Comment by soxrok2212** [comment]
Please follow the [README](https://github.com/t6x/reaver-wps-fork-t6x/blob/master/README.md).

**Comment by rofl0r** [comment]
yeah, .zip files are a windows thing, they don't know the concept of file permissions there
so you gotta use either the tar download, or git clone as @adde88 pointed out
