### ISSUE TITLE
Fail send message 2 and do not receive message 3, received nack

### ISSUE THREAD

**Issue by darkalexpp** [t6x/reaver-wps-fork-t6x#270]
Reaver 1.6.5 + pixie-dust 1.4, libpcap 1.7.4
wireless: BCM4335 MAC: 40:f3:08:4d:85:f3

I have problems getting the M3, get the M1, build the M2, send the M2, but I do not receive M3, I receive NACK.
E tried from other platforms, and if I manage to receive M3, I have tried to perform an attack without -K (without pixie dust) and if I receive M3

[+] Trying pin ********.
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[+] Received M1 message
[+] Sending M2 message
[+] Received WSC NACK
[+] Trying pin ********.
....

**Comment by soxrok2212** [comment]
WPS is locked out. Reboot the router.

**Comment by darkalexpp** [comment]
The router is not locked. When the command WASH is executed. It does not appear locked.

When I try the attack with reaver 1.4 (the one that does not have pixie dust) it executes it correctly until the m7

**Comment by soxrok2212** [comment]
Try executing first with '-N' and if that doesn't work, try with '-F'.

**Comment by kcdtv** [comment]
If you receive a NACK after sending M2 it very likely means that WPS isn't properly activated in PIN mode.
What model of router are you testing? 
Did you try using the correct PIN with -p option? 
Show us please the WPS settings from your routeur interface.

**Comment by darkalexpp** [comment]
the WPS is enabled on the router and is not blocked, and tested with other versions of reaver 1.4 that does not include pixie dust, and works well.
Try reaver 1.6.5 from another device and it works fine.
but in this device (bcm4335) it only reaches M2 and then NACK, with and without -K
Viewing the data with wireshark, I see that the router sends several M1s to the device before the device sends its M2.
It seems that it sends me NACK because the M2 is incorrect, so it opens multiple different sections.
How can I correct this?

**Comment by kcdtv** [comment]
i did not see that you had success with reaver 1.4
As suggested before use option `-N `with full verbose (`-vvv` with **3** v) and copy paste the stdout here. 
Correcting the M2 on the fly is very tricky and it would be anyway much better to fix this.
So we need to have a full stdout with `-vvv` to get as much information as possible.

**Comment by darkalexpp** [comment]
Reaver 1.6.5 + pixie-dust 1.4, libpcap 1.7.4
wireless: BCM4335  MAC: 40:f3:08:4d:85:f3

wash -i wlan0  
  
BSSID               Ch  dBm  WPS  Lck  Vendor    ESSID
--------------------------------------------------------------------------------
D8:FE:E3:82:42:08    9  -41  2.0  No   RealtekS  Conejos Patios

reaver -i wlan0 -b D8:FE:E3:82:42:08 -c 9 -K -N -vvv -F  

Reaver v1.6.5-git-12-gf936d3d WiFi Protected Setup Attack Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner

[+] Switching wlan0 to channel 9
[+] Waiting for beacon from D8:FE:E3:82:42:08
[+] Received beacon from D8:FE:E3:82:42:08
[+] Vendor: RealtekS
WPS: A new PIN configured (timeout=0)
WPS: UUID - hexdump(len=16): [NULL]
WPS: PIN - hexdump_ascii(len=8):
     31 32 33 34 35 36 37 30                           12345670        
WPS: Selected registrar information changed
WPS: Internal Registrar selected (pbc=0)
WPS: sel_reg_union
WPS: set_ie
WPS: cb_set_sel_reg
WPS: Enter wps_cg_set_sel_reg
WPS: Leave wps_cg_set_sel_reg early
WPS: return from wps_selected_registrar_changed
[+] Trying pin "12345670"
send_packet called from deauthenticate() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../80211.c:337
send_packet called from authenticate() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../80211.c:368
[+] Sending authentication request
send_packet called from associate() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../80211.c:421
[+] Sending association request
[+] Associated with D8:FE:E3:82:42:08 (ESSID: Conejos Patios)
[+] Sending EAPOL START request
send_packet called from send_eapol_start() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../send.c:48
[+] Received identity request
[+] Sending identity response
send_packet called from send_identity_response() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../send.c:81
send_packet called from resend_last_packet() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../send.c:161
send_packet called from resend_last_packet() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../send.c:161
WPS: Processing received message (len=417 op_code=4)
WPS: Received WSC_MSG
WPS: Unsupported attribute type 0x1049 len=6
WPS: Parsed WSC_MSG
WPS: Received M1
WPS: UUID-E - hexdump(len=16): 63 04 12 53 10 19 20 06 12 28 d8 fe e3 82 42 08
WPS: Enrollee MAC Address d8:fe:e3:82:42:08
WPS: Enrollee Nonce - hexdump(len=16): 45 a8 18 95 53 b8 82 70 18 a3 6f 6b 3d 66 95 d3
WPS: Enrollee Authentication Type flags 0x21
WPS: No match in supported authentication types (own 0x0 Enrollee 0x21)
WPS: Workaround - assume Enrollee does not advertise supported authentication types correctly
WPS: Enrollee Encryption Type flags 0x9
WPS: No match in supported encryption types (own 0x0 Enrollee 0x9)
WPS: Workaround - assume Enrollee does not advertise supported encryption types correctly
WPS: Enrollee Connection Type flags 0x1
WPS: Enrollee Config Methods 0x2688 [Display] [PBC]
WPS: Enrollee Wi-Fi Protected Setup State 2
WPS: Manufacturer - hexdump_ascii(len=18):
     44 2d 4c 69 6e 6b 20 43 6f 72 70 6f 72 61 74 69   D-Link Corporati
     6f 6e                                             on              
WPS: Model Name - hexdump_ascii(len=13):
     44 2d 4c 69 6e 6b 20 52 6f 75 74 65 72            D-Link Router   
WPS: Model Number - hexdump_ascii(len=8):
     44 49 52 2d 39 30 35 4c                           DIR-905L        
WPS: Serial Number - hexdump_ascii(len=13):
     32 30 30 37 30 34 31 33 2d 30 30 30 31            20070413-0001   
WPS: Primary Device Type: 6-0050F204-1
WPS: Device Name - hexdump_ascii(len=8):
     44 49 52 2d 39 30 35 4c                           DIR-905L        
WPS: Enrollee RF Bands 0x1
WPS: Enrollee Association State 0
WPS: Device Password ID 0
WPS: Enrollee Configuration Error 0
WPS: OS Version 10000000
WPS: M1 Processed
WPS: dev_pw_id checked
WPS: PBC Checked
WPS: Entering State SEND_M2
WPS: WPS_CONTINUE, Freeing Last Message
WPS: WPS_CONTINUE, Saving Last Message
WPS: returning
[+] Received M1 message
WPS: Found a wildcard PIN. Assigned it for this UUID-E
WPS: Registrar Nonce - hexdump(len=16): ed c2 a7 2a e9 02 3e a0 bf cb f3 6a 44 7f 70 7d
WPS: UUID-R - hexdump(len=16): 65 98 3b 54 a7 c0 c9 54 f4 45 db 02 08 06 83 07
WPS: Building Message M2
WPS:  * Version
WPS:  * Message Type (5)
WPS:  * Enrollee Nonce
WPS:  * Registrar Nonce
WPS:  * UUID-R
WPS:  * Public Key
WPS: Generate new DH keys
DH: private value - hexdump(len=192): 8c 6e 96 7e 59 18 c6 ff ec f0 55 6a 75 8e c6 34 9b a6 25 8d f6 d3 7f ce 8c f6 7d 91 c6 c9 7e 1e 37 2f 4d 7e cd d9 f6 07 16 b2 d6 12 4c 40 c2 64 9c ea b6 43 0b d4 1b d3 ab ad 81 51 6c 37 ee 1d 10 a5 a8 1a 86 ce 3d 5e 63 37 dd 56 64 1b 78 99 a3 bf 48 e8 c9 c6 6b ba 88 07 c8 7e 48 e1 f2 4d b3 a8 50 24 1b dc e8 b9 4d 33 c6 0f 9e 01 6f fb ea cd 38 16 02 2c 8f 91 0b 9d fc a7 46 fd a4 98 eb ac a4 11 ad 18 40 ee c6 3d e2 83 96 ed 70 80 ea ec 1b e2 91 cc 7a 59 72 54 62 f5 35 bd d2 cf 23 af 6d ad 43 d1 af 9b de 58 b7 61 37 fd 83 be 88 df 2b ad a1 4e 29 03 e5 9e a8 54 dd 75 40 4e
DH: public value - hexdump(len=192): 70 04 1f 83 87 41 c2 bc 49 9a 67 82 03 69 7f bd 7e 65 be 00 48 46 f6 c4 5a 91 4f 08 ef 43 ce de 5f 71 5f 77 d7 52 82 84 b1 9d 28 19 ec 07 33 7a c9 2d 53 1e 8e ca ae 02 83 8c a2 fa 9c 6a 1f 77 46 a8 78 07 81 81 b1 a9 3f 98 0f 68 93 0b e2 dd 32 ad 91 83 38 b3 4b ef d1 a9 d8 62 f9 62 03 40 d6 42 43 3a 9e ea b1 34 2b 66 c3 26 7d 6e 07 81 8b f4 f1 25 f2 6b 2a 63 c5 f2 c7 15 19 bd d9 1e 9a 8a b9 94 9c e7 67 14 50 5c 32 5c af 81 6e 0b 40 3e b3 9d 78 bb 14 67 bc c6 d2 73 88 d1 e3 c8 6a 56 17 9f fd 2f e9 16 ef 11 37 db 4f 18 66 9b 07 09 5d 63 d3 49 df 55 78 9b d4 b3 ce db 19 45
WPS: DH Private Key - hexdump(len=192): 8c 6e 96 7e 59 18 c6 ff ec f0 55 6a 75 8e c6 34 9b a6 25 8d f6 d3 7f ce 8c f6 7d 91 c6 c9 7e 1e 37 2f 4d 7e cd d9 f6 07 16 b2 d6 12 4c 40 c2 64 9c ea b6 43 0b d4 1b d3 ab ad 81 51 6c 37 ee 1d 10 a5 a8 1a 86 ce 3d 5e 63 37 dd 56 64 1b 78 99 a3 bf 48 e8 c9 c6 6b ba 88 07 c8 7e 48 e1 f2 4d b3 a8 50 24 1b dc e8 b9 4d 33 c6 0f 9e 01 6f fb ea cd 38 16 02 2c 8f 91 0b 9d fc a7 46 fd a4 98 eb ac a4 11 ad 18 40 ee c6 3d e2 83 96 ed 70 80 ea ec 1b e2 91 cc 7a 59 72 54 62 f5 35 bd d2 cf 23 af 6d ad 43 d1 af 9b de 58 b7 61 37 fd 83 be 88 df 2b ad a1 4e 29 03 e5 9e a8 54 dd 75 40 4e
WPS: DH own Public Key - hexdump(len=192): 70 04 1f 83 87 41 c2 bc 49 9a 67 82 03 69 7f bd 7e 65 be 00 48 46 f6 c4 5a 91 4f 08 ef 43 ce de 5f 71 5f 77 d7 52 82 84 b1 9d 28 19 ec 07 33 7a c9 2d 53 1e 8e ca ae 02 83 8c a2 fa 9c 6a 1f 77 46 a8 78 07 81 81 b1 a9 3f 98 0f 68 93 0b e2 dd 32 ad 91 83 38 b3 4b ef d1 a9 d8 62 f9 62 03 40 d6 42 43 3a 9e ea b1 34 2b 66 c3 26 7d 6e 07 81 8b f4 f1 25 f2 6b 2a 63 c5 f2 c7 15 19 bd d9 1e 9a 8a b9 94 9c e7 67 14 50 5c 32 5c af 81 6e 0b 40 3e b3 9d 78 bb 14 67 bc c6 d2 73 88 d1 e3 c8 6a 56 17 9f fd 2f e9 16 ef 11 37 db 4f 18 66 9b 07 09 5d 63 d3 49 df 55 78 9b d4 b3 ce db 19 45
WPS: DH Private Key - hexdump(len=192): 8c 6e 96 7e 59 18 c6 ff ec f0 55 6a 75 8e c6 34 9b a6 25 8d f6 d3 7f ce 8c f6 7d 91 c6 c9 7e 1e 37 2f 4d 7e cd d9 f6 07 16 b2 d6 12 4c 40 c2 64 9c ea b6 43 0b d4 1b d3 ab ad 81 51 6c 37 ee 1d 10 a5 a8 1a 86 ce 3d 5e 63 37 dd 56 64 1b 78 99 a3 bf 48 e8 c9 c6 6b ba 88 07 c8 7e 48 e1 f2 4d b3 a8 50 24 1b dc e8 b9 4d 33 c6 0f 9e 01 6f fb ea cd 38 16 02 2c 8f 91 0b 9d fc a7 46 fd a4 98 eb ac a4 11 ad 18 40 ee c6 3d e2 83 96 ed 70 80 ea ec 1b e2 91 cc 7a 59 72 54 62 f5 35 bd d2 cf 23 af 6d ad 43 d1 af 9b de 58 b7 61 37 fd 83 be 88 df 2b ad a1 4e 29 03 e5 9e a8 54 dd 75 40 4e
WPS: DH peer Public Key - hexdump(len=192): d0 14 1b 15 65 6e 96 b8 5f ce ad 2e 8e 76 33 0d 2b 1a c1 57 6b b0 26 e7 a3 28 c0 e1 ba f8 cf 91 66 43 71 17 4c 08 ee 12 ec 92 b0 51 9c 54 87 9f 21 25 5b e5 a8 77 0e 1f a1 88 04 70 ef 42 3c 90 e3 4d 78 47 a6 fc b4 92 45 63 d1 af 1d b0 c4 81 ea d9 85 2c 51 9b f1 dd 42 9c 16 39 51 cf 69 18 1b 13 2a ea 2a 36 84 ca f3 5b c5 4a ca 1b 20 c8 8b b3 b7 33 9f f7 d5 6e 09 13 9d 77 f0 ac 58 07 90 97 93 82 51 db be 75 e8 67 15 cc 6b 7c 0c a9 45 fa 8d d8 d6 61 be b7 3b 41 40 32 79 8d ad ee 32 b5 dd 61 bf 10 5f 18 d8 92 17 76 0b 75 c5 d9 66 a5 a4 90 47 2c eb a9 e3 b4 22 4f 3d 89 fb 2b
DH: shared key - hexdump(len=192): f9 27 2b 51 c1 30 65 38 33 c9 67 5a b9 cd fc 64 22 90 91 e9 93 ab 1d 65 c9 e0 16 13 a2 9b f3 3a df 67 be e8 ba a0 63 ff bd c4 d6 f0 6d ae f9 cd 06 f8 4f 89 a7 f8 ae cc cb 97 0a d2 76 64 d5 76 8d 57 cc 95 b8 4e 10 cf 67 53 9b 46 66 18 51 27 34 5f d7 40 80 02 67 bb 75 80 39 3a eb 1b 00 89 19 a3 64 1f c0 3b bc af 9a 0f a1 09 12 b4 61 54 97 cb c5 b4 e8 0a f2 24 7f c0 b4 6a 48 86 60 4a 9d 25 55 e9 29 19 16 c3 f6 75 95 ef 9c c8 4a 9b 15 33 e7 b5 56 34 fe 56 6a 78 b4 b3 91 d2 4d 34 af 00 5d ae a3 0c 82 0d c8 25 f0 3d 21 53 13 84 7e 56 ae 1b d3 ad 67 b5 9b 75 2f 5a 2d 62 0d f5
WPS: DH shared key - hexdump(len=192): f9 27 2b 51 c1 30 65 38 33 c9 67 5a b9 cd fc 64 22 90 91 e9 93 ab 1d 65 c9 e0 16 13 a2 9b f3 3a df 67 be e8 ba a0 63 ff bd c4 d6 f0 6d ae f9 cd 06 f8 4f 89 a7 f8 ae cc cb 97 0a d2 76 64 d5 76 8d 57 cc 95 b8 4e 10 cf 67 53 9b 46 66 18 51 27 34 5f d7 40 80 02 67 bb 75 80 39 3a eb 1b 00 89 19 a3 64 1f c0 3b bc af 9a 0f a1 09 12 b4 61 54 97 cb c5 b4 e8 0a f2 24 7f c0 b4 6a 48 86 60 4a 9d 25 55 e9 29 19 16 c3 f6 75 95 ef 9c c8 4a 9b 15 33 e7 b5 56 34 fe 56 6a 78 b4 b3 91 d2 4d 34 af 00 5d ae a3 0c 82 0d c8 25 f0 3d 21 53 13 84 7e 56 ae 1b d3 ad 67 b5 9b 75 2f 5a 2d 62 0d f5
WPS: DHKey - hexdump(len=32): 7b 49 1e 35 c6 ce ad 8f f0 4c d2 e0 bf e5 cc f2 b3 69 2e cc 06 04 7c a5 f1 67 30 e6 57 2e 20 b7
WPS: KDK - hexdump(len=32): fe 20 d0 09 81 d5 99 9b 73 f2 50 d7 fc c5 78 46 46 03 14 df f7 ff 7e 0f 21 9b ca 97 5e be 22 b8
WPS: AuthKey - hexdump(len=32): 70 fe b3 04 6f 5d 69 5a 88 1d a3 ed 38 41 38 f2 63 21 2b c0 ba 47 56 b3 6a c3 ca 7d 04 02 67 b2
WPS: KeyWrapKey - hexdump(len=16): 3a d8 a5 9e 6c 14 42 e1 38 01 07 90 d2 27 c1 d3
WPS: EMSK - hexdump(len=32): 2d c8 92 8c 72 7e 32 8d 0a 2f 66 be 7e 76 b3 66 a3 49 46 e3 a3 f2 aa 76 6e 00 76 63 38 7f 8d d7
WPS:  * Authentication Type Flags
WPS:  * Encryption Type Flags
WPS:  * Connection Type Flags
WPS:  * Config Methods (8c)
WPS:  * Manufacturer
WPS:  * Model Name
WPS:  * Model Number
WPS:  * Serial Number
WPS:  * Primary Device Type
WPS:  * Device Name
WPS:  * RF Bands (0)
WPS:  * Association State
WPS:  * Configuration Error (0)
WPS:  * Device Password ID (0)
WPS:  * OS Version
WPS:  * Authenticator
[+] Sending M2 message
send_packet called from send_msg() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../send.c:116
send_packet called from resend_last_packet() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../send.c:161
send_packet called from resend_last_packet() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../send.c:161
WPS: Processing received message (len=66 op_code=3)
WPS: Received WSC_NACK
WPS: Unsupported attribute type 0x1049 len=6
WPS: Enrollee terminated negotiation with Configuration Error 68
[+] Received WSC NACK
WPS: Building Message WSC_NACK
WPS:  * Version
WPS:  * Message Type (14)
WPS:  * Enrollee Nonce
WPS:  * Registrar Nonce
WPS:  * Configuration Error (0)
[+] Sending WSC NACK
send_packet called from send_msg() //home/alex/Escritorio/Krack/reaver-wps-android/src/android_external_libpcap/../send.c:116
[!] WPS transaction failed (code: 0x04), re-trying last pin
WPS: Invalidating used wildcard PIN
WPS: Invalidated PIN for UUID - hexdump(len=16): 63 04 12 53 10 19 20 06 12 28 d8 fe e3 82 42 08
WPS: A new PIN configured (timeout=0)
WPS: UUID - hexdump(len=16): [NULL]
WPS: PIN - hexdump_ascii(len=8):
     31 32 33 34 35 36 37 30                           12345670        


And in the same device:
Reaver 1.4, libpcap 1.7.4

reaver -i wlan0 -b D8:FE:E3:82:42:08 -c 9  -N -vvv

 [+] Switching wlan0 to channel 9
[+] Waiting for beacon from D8:FE:E3:82:42:08
DEBUG external/reaver-wps/80211.c (229): Red AP beacon
DEBUG external/reaver-wps/80211.c (235): deauthenticate() done
DEBUG external/reaver-wps/80211.c (241): authenticate() done
DEBUG external/reaver-wps/80211.c (245): end while associate_recv_loop()
DEBUG external/reaver-wps/80211.c (250): tries < MAX_AUTH_TRIES
DEBUG external/reaver-wps/80211.c (256): associate() done in loop
[+] Associated with D8:FE:E3:82:42:08 (ESSID: Conejos Patios)
[+] Trying pin 12345670
DEBUG external/reaver-wps/80211.c (229): Red AP beacon
DEBUG external/reaver-wps/80211.c (235): deauthenticate() done
DEBUG external/reaver-wps/80211.c (241): authenticate() done
DEBUG external/reaver-wps/80211.c (245): end while associate_recv_loop()
DEBUG external/reaver-wps/80211.c (250): tries < MAX_AUTH_TRIES
DEBUG external/reaver-wps/80211.c (256): associate() done in loop
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[+] Received M1 message
[+] Sending M2 message
[+] Received M3 message
[+] Sending M4 message
[+] Received WSC NACK
[+] Sending WSC NACK
[+] Trying pin 00005678

**Comment by rofl0r** [comment]
thanks for the detailed output. would you mind checking a few of the other releases from here: https://github.com/t6x/reaver-wps-fork-t6x/releases to find out which one is the first "bad" release ?

**Comment by darkalexpp** [comment]
Hello everyone, I was finally able to solve the problem of the badly generated M2 message, everything was a bad configuration that occurred at the time of compiling, in the file crypto/crypto_internal-modexp.c specifically by the file bignum.c
the data was being truncated.

**Comment by kcdtv** [comment]
Thanks for your feedback
Did you use `./configure` before compiling?

**Comment by darkalexpp** [comment]
Yes, I use ./configure before compiling.

**Comment by darkalexpp** [comment]
Now I have another problem, I already received the M3 but sometimes it executes pixie dust, and other times it passes and sends M4 to the router, and no pixie dust is activated, which leads to the router being locked.
this only happens in reaver 1.6.5, probe with 1.6b and it works correctly,
throughout the day I will try other versions

**Comment by soxrok2212** [comment]
Please open a new issue for this.

**Comment by Mostapha2005** [comment]
please i need a solution , in the stat i was using waicut without any problems but now when im starting the pixie dust , it,s just stopping at M1 and showing me *THE RPC SERVER IS UNAVAILABLE*

**Comment by rofl0r** [comment]
this is not a waicut help forum, bring it there.
