### ISSUE TITLE
reaver stops guessing pins when use with -K

### ISSUE THREAD

**Issue by logan001** [t6x/reaver-wps-fork-t6x#272]
I just notice that when i try to use reaver with -K option reaver will stop with one attempt and that;s it.

Testing on the router reaver with a pin (not the router pin) seems to make pixie discover the correct pin
Changing the pin provided to reaver to another random one a second time resulted in failure for pixie.

Is there any option to make reaver behave like without -K but to also use pixiewps after each pin test so that reaver can keep guessing the pin but also to pass the corresponding variables to pixie

Edit: It seems that the router will not return the same variables for the same pin. It seems that the router only worked on 1st attempt. the rest of the attempts even with the 1st pin made pixie to be unable to find the pin.

**Comment by rofl0r** [comment]
pixiedust attacks either works always, or never (with a specific router). so there's no reason to keep testing the attack over and over.

**Comment by logan001** [comment]
if that is so than why the variable are different with the same pin?

**Comment by rofl0r** [comment]
which variable ?

**Comment by logan001** [comment]
s/z/a/n/r

**Comment by rofl0r** [comment]
those are cryptographic nonces. they're supposed to be different each time...

**Comment by logan001** [comment]
seems that i can use  reaver-wps-fork-t6x/tools/logfilter.py and -vvv output

**Comment by logan001** [comment]
strange. why would pixie need them if they are suppose to change. and why would pixie will not work with different set of variables?
well i'm not into programing/wifi protocols/whatever.
for me this seems strange.

**Comment by kimocoder** [comment]
WPS pin attack is one type of attack, pixiewps is another attack vector again..

**Comment by rofl0r** [comment]
see the README and the wiki on this repo. there are articles and links to articles which explain in great detail how these attacks works.
