### ISSUE TITLE
RTL8812AU (AWUS036ACH) 5.6.4.2 Timeout

### ISSUE THREAD

**Issue by Error0x00000001** [t6x/reaver-wps-fork-t6x#302]
root@book:/home/igor/rtl8812au# reaver 
Reaver v1.6.5-git-70-g1c86168 WiFi Protected Setup Attack Tool
######################
5.6.4.2 - Not Worked 
5.2.20.2  Worked
######################
[+] Trying pin "12345670"
[+] Sending authentication request
[+] Sending association request
[+] Associated with F8:BF:09:8A:E4:10 (ESSID: MgtsGpon83)
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[+] Received deauth request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[+] Received deauth request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[!] WARNING: 10 successive start failures
[+] Sending EAPOL START request
[+] Sending WSC NACK
[!] WPS transaction failed (code: 0x02), re-trying last pin
[+] Trying pin "12345670"

**Comment by soxrok2212** [comment]
*sigh* Perhaps we should add an issue template... can you give us any information besides it doesn’t work?

**Comment by Error0x00000001** [comment]
Kali, image 5.2*, 5.3*,5.4*
Wash worked
Reaver Not worked (Timeout only)

**Comment by rofl0r** [comment]
https://github.com/t6x/reaver-wps-fork-t6x/wiki/Troubleshooting

**Comment by Error0x00000001** [comment]
Makr clean - Fine!
Work!
