### ISSUE TITLE
Wps not found

### ISSUE THREAD

**Issue by Tariq888** [t6x/reaver-wps-fork-t6x#304]
Why wps not didn't found ?
reaver -i wlan0mon -b D8:32:14:C8:0A:18 -vv -N -K 1
![Screenshot from 2020-02-13 14-28-19](https://user-images.githubusercontent.com/46182304/74420528-976eee80-4e19-11ea-8ac4-891d28f5db33.png)

**Comment by soxrok2212** [comment]
Probably because the router isn’t vulnerable. You can try pixiewps manually if you want to verify.
