### ISSUE TITLE
Which is my Wpa Psk

### ISSUE THREAD

**Issue by mamilux** [t6x/reaver-wps-fork-t6x#305]
Hi everyone. I have wps pin router tried to crack with reaver but result is strange. Can anyone help me. Question is which one is Password? Thanks in advance. 
![IMG_20200214_225658](https://user-images.githubusercontent.com/6977384/74575766-9087dd80-4fcb-11ea-8773-413e3c71a94f.jpg)

**Comment by soxrok2212** [comment]
Nothing is, you need to re-run reaver with the `-p <pincode>` option to get the key.

**Comment by feitoi** [comment]
And **without** `-K`

**Comment by mamilux** [comment]
Thanks for Answers. Unfortunately got locked wps :(
