### ISSUE TITLE
Receive timeout occurred Sending EAPOL START request

### ISSUE THREAD

**Issue by helloful** [t6x/reaver-wps-fork-t6x#321]
Hello，I got this question all the time,have any suggestion?
`[+] Waiting for beacon from 28:9E:97:AA:1F:CC
[+] Switching wlan0mon to channel 1
[+] Switching wlan0mon to channel 2
[+] Switching wlan0mon to channel 3
[+] Switching wlan0mon to channel 4
[+] Switching wlan0mon to channel 5
[+] Switching wlan0mon to channel 6
[+] Switching wlan0mon to channel 7
[+] Switching wlan0mon to channel 8
[+] Switching wlan0mon to channel 9
[+] Switching wlan0mon to channel 10
[+] Received beacon from 28:9E:97:AA:1F:CC
[+] Vendor: RalinkTe
[+] Trying pin "12345670"
[+] Sending authentication request
[+] Sending association request
[+] Associated with 28:9E:97:AA:1F:CC (ESSID: ChinaNet-J9SY)
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request
[!] WARNING: Receive timeout occurred
[+] Sending EAPOL START request

`

**Comment by rofl0r** [comment]
i'd suggest to read the wiki article "troubleshooting guide" and generally moving the antenna closer to the target. let us know if you have further issues

**Comment by KikoTs** [comment]
I have the same issue on TL-WN722N v1 is it the card or do i need some type of drivers because bully also doesnt work

**Comment by rofl0r** [comment]
TL-WN722N v1 is one of the best cards for this purpose, but it doesn't have a lot of TX power. did you try -N command line and read the troubleshooting guide ?

**Comment by soxrok2212** [comment]
Closing as no response received. Please re-open if issue persists and troubleshooting isn't helping.
