### ISSUE TITLE
Trying pin "12345670"

### ISSUE THREAD

**Issue by VajiraSoul** [t6x/reaver-wps-fork-t6x#340]
Reaver remains stuck on trying the same pin over and over

Trying pin "12345670"
send_packet called from deauthenticate() 80211.c:xxx
send_packet called from authenticate() 80211.c:xxx
[+] Sending authentication request
send_packet called from associate() 80211.c:xxx
[+] Sending association request
[+] Associated with xx:xx:xx:xx:xx:xx (ESSID: xxxxx_xxxxxxx)
[+] Sending EAPOL START request
send_packet called from send_eapol_start() send.c:48
send_packet called from resend_last_packet() send.c:161
send_packet called from resend_last_packet() send.c:161
send_packet called from resend_last_packet() send.c:161
send_packet called from resend_last_packet() send.c:161

I tried every solution suggested online: add no-nacks, -S , --no-associate and association with aireplay-ng, in combinations as well. I also tried to downgrade the version but unsuccesfully.
Thanks in advance for the help.

**Comment by rofl0r** [comment]
your question is addressed in point 4 of troubleshooting guide. https://github.com/t6x/reaver-wps-fork-t6x/wiki/Troubleshooting
