### ISSUE TITLE
Doesn't look for networks with WPS

### ISSUE THREAD

**Issue by Uefi1** [t6x/reaver-wps-fork-t6x#344]
Hi, doesn't look for networks with WPS tried different versions Reaver fork, WASH just doesn't open =(
It works on another system, I realized that you need some of the libraries since I was adding the module libraris.xzm and work here ! What libraries might be missing?

**Comment by soxrok2212** [comment]
Hi! Read here https://github.com/t6x/reaver-wps-fork-t6x#build-time-dependencies

**Comment by Uefi1** [comment]
> Hi! Read here https://github.com/t6x/reaver-wps-fork-t6x#build-time-dependencies
I'm not dumb i installed it
