### ISSUE TITLE
Reaver stuck on send_packet called from resend _last_packet() send.c.161 while using pixie dust attack

### ISSUE THREAD

**Issue by Abhinav413652** [t6x/reaver-wps-fork-t6x#376]
![16919138522518469776776091532281](https://github.com/t6x/reaver-wps-fork-t6x/assets/74493620/5eab0a2b-86a1-455e-a778-add901e60faf)

The commands I ran:
./reaver -i wlan0 -b bssid -vvv -K
reaver -i wlan0 -b bssid -vvv -K

I've never successfully executed reaver. I'm trying the pixie dust attack but it always fails. I've cloned the repo successfully but reaver always gives me the same output. I've tried multiple commands but nothing seems to work.

**Comment by soxrok2212** [comment]
What is the model of the AP? Is WPS enabled and not locked?

**Comment by Abhinav413652** [comment]
AP is of RaLink and WPS is enabled and is not locked.

**Comment by Abhinav413652** [comment]
Btw I closed this by mistake.

**Comment by october262** [comment]
if you try your reaver command again without the pixie dust command
are you getting  Received M1 message Sending M2 message Received M3 message
Sending M4 message ??

**Comment by rofl0r** [comment]
OP doesnt even get associated according to screenshot, so he's probably too far away or his dongle doesnt support injection. read the Troubleshooting article on the wiki here.

**Comment by Abhinav413652** [comment]
I'm not far, I'm very close to the target

**Comment by soxrok2212** [comment]
What happens if you stand right next to it?

**Comment by Abhinav413652** [comment]
My wifi adapter supports packet injection as it can switch to monitor mode. I was watching a lecture and he mentioned that latest versions of reaver have this error. Is it so?

**Comment by october262** [comment]
try reaver like this - reaver -i wlan0 -b F2:ED:B8:5D:84:17 -vv -P your routers pin #
see if it work this way.

**Comment by Abhinav413652** [comment]
I'll try tomorrow thx 🙏 🙏 for the response

**Comment by Abhinav413652** [comment]
I tried and still it's giving me the same error

**Comment by rofl0r** [comment]
> My wifi adapter supports packet injection as it can switch to monitor mode

that's a wrong conclusion. some drivers support one, but not the the other, even if not by design then by kernel bugs. make the injection test according to the troubleshooting guide and post the result. my patience is about to run out.

**Comment by Abhinav413652** [comment]
see my adapter can do packet injection as it did crack TP LINK wps using my adapter using wifite.
is there any tutorial which works now?? as wifite and airegeddon are also failing...

**Comment by soxrok2212** [comment]
Unable to provide necessary information, cannot prove ownership of target AP.
