### ISSUE TITLE
What is the relationship between reaver-wps-fork-t6x and  Pixiewps 1.4 WPS pixie-dust attack tool?

### ISSUE THREAD

**Issue by getr00t** [t6x/reaver-wps-fork-t6x#380]
Is reaver-wps-fork-t6x an upgrade fix for Pixiewps 1.4 WPS pixie-dust attack tool? Or what is the relationship, my kali system comes with Pixiewps 1.4 version, no reaver-wps-fork-t6x 1.6 version Is it necessary for me to install reaver-wps-fork-t6x 1.6 manually?
![image](https://github.com/t6x/reaver-wps-fork-t6x/assets/12257416/d28118a4-8d4c-4cae-a74c-9ba7aeff364e)

**Comment by soxrok2212** [comment]
Pixiewps functionality is directly integrated into Reaver. You need both installed.
