### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by DarkJester** [t6x/reaver-wps-fork-t6x#4]
new compile on kali gives no output old version of wash works fine

root@ikali:~/reaver-wps-fork-t6x/src# ./wash -i mon0 -s

Wash v1.5.1 WiFi Protected Setup Scan Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>
mod by t6_x <t6_x@hotmail.com>
mod by DataHead

BSSID                  Channel       RSSI       WPS Version       WPS Locked        ESSID
---------------------------------------------------------------------------------------------------------------
^C
root@ikali:~/reaver-wps-fork-t6x/src# ./wash -i mon0 

Wash v1.5.1 WiFi Protected Setup Scan Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>
mod by t6_x <t6_x@hotmail.com>
mod by DataHead

BSSID                  Channel       RSSI       WPS Version       WPS Locked        ESSID
---------------------------------------------------------------------------------------------------------------
^C

**Comment by d8tahead** [comment]
Try with -C

**Comment by DarkJester** [comment]
same result no output. i did get some warnings durring compile but i made sure it install all the deps first

**Comment by d8tahead** [comment]
i've done a fresh compile and install with the lastest build. i can not reproduce this error. 

may i reccomend that you either do a restart of the system and put your device into monitor mode and run wash with the following: wash - i <mondevice> -C -s

if that fails, please re compile and make sure dependencies are correctly installed.

if the problem continues after so, please report back with as much info as possible.

-Cheers

**Comment by DarkJester** [comment]
please see huge paste below;

root@ikali:~/reaver-wps-fork-t6x/src# apt-get install libpcap-dev aircrack-ng sqlite3 libsqlite3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
aircrack-ng is already the newest version.
libpcap-dev is already the newest version.
libsqlite3-dev is already the newest version.
sqlite3 is already the newest version.
The following packages were automatically installed and are no longer required:
  libafpclient0 libcrypt-passwdmd5-perl libgadu3 libhackrf libmozjs24d libtsk3-3 linux-headers-3.14-kali1-amd64 linux-headers-3.14-kali1-common
  linux-headers-3.18.0-kali1-amd64 linux-headers-3.18.0-kali1-common linux-kbuild-3.14 python-flask python-itsdangerous python-werkzeug unrar-free xulrunner-24.0
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@ikali:~/reaver-wps-fork-t6x/src# make clean
make: *** No rule to make target `clean'.  Stop.
root@ikali:~/reaver-wps-fork-t6x/src# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for pcap_open_live in -lpcap... yes
checking for sqlite3_open in -lsqlite3... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for stdint.h... (cached) yes
checking for string.h... (cached) yes
checking pcap.h usability... yes
checking pcap.h presence... yes
checking for pcap.h... yes
checking sqlite3.h usability... yes
checking sqlite3.h presence... yes
checking for sqlite3.h... yes
configure: creating ./config.status
config.status: creating Makefile
root@ikali:~/reaver-wps-fork-t6x/src# make
(cd utils && make)
make[1]: Entering directory `/root/reaver-wps-fork-t6x/src/utils'
  CC  base64.c
common.c: In function ‘pingen_dlink’:
common.c:534:20: warning: variable ‘serial_len’ set but not used [-Wunused-but-set-variable]
common.c:534:9: warning: variable ‘mac_len’ set but not used [-Wunused-but-set-variable]
  CC  common.c
  CC  ip_addr.c
  CC  radiotap.c
  CC  trace.c
  CC  uuid.c
  CC  wpa_debug.c
  CC  wpabuf.c
  CC  os_unix.c
  CC  eloop.c
ar crT libutils.a base64.o common.o ip_addr.o radiotap.o trace.o uuid.o wpa_debug.o wpabuf.o os_unix.o eloop.o
make[1]: Leaving directory `/root/reaver-wps-fork-t6x/src/utils'
(cd tls && make)
make[1]: Entering directory `/root/reaver-wps-fork-t6x/src/tls'
  CC  asn1.c
In file included from bignum.c:21:0:
libtommath.c: In function ‘mp_exptmod’:
libtommath.c:580:9: warning: variable ‘dr’ set but not used [-Wunused-but-set-variable]
  CC  bignum.c
  CC  pkcs1.c
  CC  pkcs5.c
  CC  pkcs8.c
  CC  rsa.c
  CC  tlsv1_client.c
  CC  tlsv1_client_read.c
  CC  tlsv1_client_write.c
  CC  tlsv1_common.c
  CC  tlsv1_cred.c
  CC  tlsv1_record.c
  CC  tlsv1_server.c
tlsv1_server_read.c: In function ‘tls_process_client_key_exchange_rsa’:
tlsv1_server_read.c:474:9: warning: variable ‘encr_len’ set but not used [-Wunused-but-set-variable]
  CC  tlsv1_server_read.c
  CC  tlsv1_server_write.c
  CC  x509v3.c
ar crT libtls.a asn1.o bignum.o pkcs1.o pkcs5.o pkcs8.o rsa.o tlsv1_client.o tlsv1_client_read.o tlsv1_client_write.o tlsv1_common.o tlsv1_cred.o tlsv1_record.o tlsv1_server.o tlsv1_server_read.o tlsv1_server_write.o x509v3.o
make[1]: Leaving directory `/root/reaver-wps-fork-t6x/src/tls'
(cd crypto && make)
make[1]: Entering directory `/root/reaver-wps-fork-t6x/src/crypto'
  CC  aes-cbc.c
  CC  aes-ctr.c
  CC  aes-eax.c
  CC  aes-encblock.c
  CC  aes-internal.c
  CC  aes-internal-dec.c
  CC  aes-internal-enc.c
  CC  aes-omac1.c
  CC  aes-unwrap.c
  CC  aes-wrap.c
  CC  des-internal.c
  CC  dh_group5.c
  CC  dh_groups.c
  CC  md4-internal.c
  CC  md5.c
md5-internal.c: In function ‘MD5Final’:
md5-internal.c:185:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
md5-internal.c:186:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CC  md5-internal.c
  CC  md5-non-fips.c
  CC  milenage.c
  CC  ms_funcs.c
  CC  rc4.c
  CC  sha1.c
  CC  sha1-internal.c
  CC  sha1-pbkdf2.c
  CC  sha1-tlsprf.c
  CC  sha1-tprf.c
  CC  sha256.c
  CC  sha256-internal.c
  CC  crypto_internal.c
  CC  crypto_internal-cipher.c
  CC  crypto_internal-modexp.c
  CC  crypto_internal-rsa.c
  CC  tls_internal.c
  CC  fips_prf_internal.c
ar crT libcrypto.a aes-cbc.o aes-ctr.o aes-eax.o aes-encblock.o aes-internal.o aes-internal-dec.o aes-internal-enc.o aes-omac1.o aes-unwrap.o aes-wrap.o des-internal.o dh_group5.o dh_groups.o md4-internal.o md5.o md5-internal.o md5-non-fips.o milenage.o ms_funcs.o rc4.o sha1.o sha1-internal.o sha1-pbkdf2.o sha1-tlsprf.o sha1-tprf.o sha256.o sha256-internal.o crypto_internal.o crypto_internal-cipher.o crypto_internal-modexp.o crypto_internal-rsa.o tls_internal.o fips_prf_internal.o
make[1]: Leaving directory `/root/reaver-wps-fork-t6x/src/crypto'
(cd wps && make)
make[1]: Entering directory `/root/reaver-wps-fork-t6x/src/wps'
gcc -I../utils -I ../ wps_attr_build.c -c
gcc -I../utils -I ../ wps_attr_parse.c -c
gcc -I../utils -I ../ wps_attr_process.c -c
gcc -I../utils -I ../ wps.c -c
gcc -I../utils -I ../ wps_common.c -c
gcc -I../utils -I ../ wps_dev_attr.c -c
wps_dev_attr.c: In function ‘wps_process_manufacturer’:
wps_dev_attr.c:195:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
wps_dev_attr.c: In function ‘wps_process_model_number’:
wps_dev_attr.c:248:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
wps_dev_attr.c: In function ‘wps_process_serial_number’:
wps_dev_attr.c:278:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
wps_dev_attr.c:294:3: warning: passing argument 1 of ‘pingen_belkin’ makes pointer from integer without a cast [enabled by default]
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘int’
wps_dev_attr.c:294:3: warning: passing argument 2 of ‘pingen_belkin’ discards ‘const’ qualifier from pointer target type [enabled by default]
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘const u8 *’
wps_dev_attr.c:303:3: warning: passing argument 1 of ‘pingen_dlink’ makes pointer from integer without a cast [enabled by default]
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:448:5: note: expected ‘char *’ but argument is of type ‘int’
wps_dev_attr.c:303:3: warning: passing argument 2 of ‘pingen_dlink’ discards ‘const’ qualifier from pointer target type [enabled by default]
In file included from ../wps.h:40:0,
                 from ../defs.h:45,
                 from ../globule.h:37,
                 from wps_dev_attr.c:15:
../utils/common.h:448:5: note: expected ‘char *’ but argument is of type ‘const u8 *’
gcc -I../utils -I ../ wps_enrollee.c -c
gcc -I../utils -I ../ wps_registrar.c -c
gcc -I../utils -I ../ wps_ufd.c -c
make[1]: Leaving directory `/root/reaver-wps-fork-t6x/src/wps'
(cd lwe && make BUILD_STATIC=y libiw.a)
make[1]: Entering directory `/root/reaver-wps-fork-t6x/src/lwe'
cp wireless.21.h wireless.h
gcc -Os -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wpointer-arith -Wcast-qual -Winline -I. -MMD     -fPIC -c -o iwlib.so iwlib.c
rm -f libiw.a
ar cru libiw.a iwlib.so
ranlib libiw.a
make[1]: Leaving directory `/root/reaver-wps-fork-t6x/src/lwe'
(cd libwps && make)
make[1]: Entering directory `/root/reaver-wps-fork-t6x/src/libwps'
gcc -Wall libwps.c -c
libwps.c: In function ‘parse_wps_parameters’:
libwps.c:29:12: warning: variable ‘data_len’ set but not used [-Wunused-but-set-variable]
make[1]: Leaving directory `/root/reaver-wps-fork-t6x/src/libwps'
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 globule.c -c 
globule.c: In function ‘set_p1_index’:
globule.c:110:9: warning: implicit declaration of function ‘cprintf’ [-Wimplicit-function-declaration]
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps argsparser.c -c
argsparser.c: In function ‘process_arguments’:
argsparser.c:96:17: warning: implicit declaration of function ‘set_op_gen_pin’ [-Wimplicit-function-declaration]
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 init.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 misc.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps sql.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 builder.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 crc.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps 80211.c -c
80211.c: In function ‘read_ap_beacon’:
80211.c:76:12: warning: variable ‘tag_offset’ set but not used [-Wunused-but-set-variable]
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 iface.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps wpsmon.c *.o libwps/*.o wps/*.o tls/bignum.o tls/libtls.a utils/libutils.a crypto/libcrypto.a lwe/libiw.a -ldl -lm -lpcap -lsqlite3  -o wash
wpsmon.c: In function ‘parse_wps_settings’:
wpsmon.c:419:7: warning: pointer targets in passing argument 2 of ‘strcat’ differ in signedness [-Wpointer-sign]
In file included from libwps/libwps.h:18:0,
                 from wpsmon.h:41,
                 from wpsmon.c:34:
/usr/include/string.h:136:14: note: expected ‘const char * __restrict__’ but argument is of type ‘unsigned char *’
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps sigint.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 sigalrm.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 keys.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 pins.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 send.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps exchange.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps session.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps cracker.c -c
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps wpscrack.c *.o libwps/*.o wps/*.o tls/bignum.o tls/libtls.a utils/libutils.a crypto/libcrypto.a lwe/libiw.a -ldl -lm -lpcap -lsqlite3  -o reaver
wpscrack.c: In function ‘main’:
wpscrack.c:40:33: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
root@ikali:~/reaver-wps-fork-t6x/src# ifconfig
eth0      Link encap:Ethernet  HWaddr 1c:c1:de:b5:92:1d  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:20 Memory:d4500000-d4520000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:328 errors:0 dropped:0 overruns:0 frame:0
          TX packets:328 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:97469 (95.1 KiB)  TX bytes:97469 (95.1 KiB)

wlan0     Link encap:Ethernet  HWaddr 00:27:10:d9:29:3c  
          inet addr:192.168.1.9  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::227:10ff:fed9:293c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6363 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3999 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5381726 (5.1 MiB)  TX bytes:513702 (501.6 KiB)

wlan3     Link encap:UNSPEC  HWaddr 00-C0-CA-6D-0B-C0-3A-31-00-00-00-00-00-00-00-00  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:20596 errors:0 dropped:17365 overruns:0 frame:0
          TX packets:42 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3059616 (2.9 MiB)  TX bytes:8276 (8.0 KiB)

root@ikali:~/reaver-wps-fork-t6x/src# ./wash -i wlan3 -C -s

Wash v1.5.1 WiFi Protected Setup Scan Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>
mod by t6_x <t6_x@hotmail.com>
mod by DataHead

BSSID                  Channel       RSSI       WPS Version       WPS Locked        ESSID
---------------------------------------------------------------------------------------------------------------
^C
root@ikali:~/reaver-wps-fork-t6x/src# uname -a
Linux ikali 3.12-kali1-amd64 #1 SMP Debian 3.12.6-2kali1 (2014-01-06) x86_64 GNU/Linux
root@ikali:~/reaver-wps-fork-t6x/src# ./wash -i wlan3 -C -s

Wash v1.5.1 WiFi Protected Setup Scan Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>
mod by t6_x <t6_x@hotmail.com>
mod by DataHead

BSSID                  Channel       RSSI       WPS Version       WPS Locked        ESSID
---------------------------------------------------------------------------------------------------------------

**Comment by d8tahead** [comment]
are you doing this before using wash?
airmon-ng start wlan3

or

ifconfig wlan3 down && iwconfig wlan3 mode monitor && ifconfig wlan3 up

and for the sake of: airmon-ng start wlan3    bring down the wlan3 interface before hand
ifconfig wlan3 down

**Comment by DarkJester** [comment]
i tried airmon-ng and the manual ifconfig way of putting the device in monitor mode i rebooted etc. the installed version of wash works fine. new version of reaver works just new wash is broken

root@ikali:~/reaver-wps-fork-t6x/src# wash -i wlan3

Wash v1.4 WiFi Protected Setup Scan Tool
Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>

BSSID                  Channel       RSSI       WPS Version       WPS Locked        ESSID
---------------------------------------------------------------------------------------------------------------
E0:91:F5:6F:D2:2A       1            -52        1.0               No                Artavia

**Comment by t6x** [comment]
What system are you using? Kernel version and what wifi adapter?

Some processes may influence the airmon-ng, as wpa_supplicant and etc, try killall wpa_supplicant and verifies that the wash back to work.

Any application that uses the wifi driver influences the airmon

**Comment by DarkJester** [comment]
all proccess that effect wifi killed.

see output below of kernel and kali version

root@ikali:~/reaver-wps-fork-t6x/src# uname -a
Linux ikali 3.12-kali1-amd64 #1 SMP Debian 3.12.6-2kali1 (2014-01-06) x86_64 GNU/Linux
root@ikali:~/reaver-wps-fork-t6x/src# cat /etc/issue
Kali GNU/Linux 1.1.0 \n \l

root@ikali:~/reaver-wps-fork-t6x/src# cat /etc/debian_version 
Kali Linux 1.1.0
root@ikali:~/reaver-wps-fork-t6x/src# 

WIFI adapter 
Bus 002 Device 003: ID 0bda:8187 Realtek Semiconductor Corp. RTL8187 Wireless Adapter

Wash v1.4 WiFi Protected Setup Scan Tool installed from Kali repo works fine,  New wash has no output

**Comment by t6x** [comment]
The system is 64-bit may be the problem.
I tested here in a kali 64bit and everything worked normally, but the 64bit is very problematic with the aircrack-ng.
There are many problems with drivers that only compiling reaver not be resolved.
You could test with kali 32bit?

**Comment by DarkJester** [comment]
I will install 32 bit and test

**Comment by kcdtv** [comment]
@ DarkJester
"root@ikali:~/reaver-wps-fork-t6x/src# wash -i wlan3"
You have to use the interface IN mode monitor 
wash -i wlan3mon  /   wash -i mon3
@ t6x
"The system is 64-bit may be the problem."
No worries with this ;) I only use the last 64amd kali linux / Xubutnu version with rtl8187l and everything goes fine with both them

**Comment by d8tahead** [comment]
64bit kali 1.1.0 and all working fine here aswel. Your system might be
broken in more than just the dependencies or there is improper installing
of the new reaver / wash. Instead of using wash directly from the build
directory, please run make install to ensure its placement on the OS is
where it should be.  and run it from global.

**Comment by d8tahead** [comment]
I will also be doing an in-depth debug analysis of this issue in a day or two when i have a bit more time

**Comment by d8tahead** [comment]
I may need you to participate in some installation of a few tools since i can not replicate this issue. I will be providing a special use case makefile for you in a day or two when i have the time, it will add compiling with debug and 01 or 00 flags and then will need you to install valgrind and do a valgrind --leak-check-full as a prefix to your segfault wash command

**Comment by DarkJester** [comment]
This works on a pure 32bit system fresh install. My 64bit system is actually multi arch so maybe im pulling in something I shouldnt durrin compile time. also please note
@kcdtv 
""root@ikali:~/reaver-wps-fork-t6x/src# wash -i wlan3"
You have to use the interface IN mode monitor
wash -i wlan3mon / wash -i mon3"
My interface IS in monitor mode. doing ifconfig down; iwconfig wlan3 mode monitor; ifconfig up places the wlan3 in monitor mode but does not make a psuedo monX interface.
 @d8tahead 
Happy to run any tests you need.

**Comment by crushedice2000** [comment]
I'm facing the same problem. I think that this happens because the latest version of `libpcap` is not supported by this reaver (this also happens with the original one)
