### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by mamayoleksandr** [t6x/reaver-wps-fork-t6x#48]
wpscrack.c: In function ‘main’:
wpscrack.c:40:33: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
     int ret_val = EXIT_FAILURE, r = 0;

**Comment by kcdtv** [comment]
This is not an error but  a warning about a non used variable in  kind of "routine" stdout. 
It doesn't mean compilation has failed and you could install reaver with make install (as root).
