### ISSUE TITLE
Problem with  TP-LINK TD-W8961ND

### ISSUE THREAD

**Issue by Gitussef** [t6x/reaver-wps-fork-t6x#5]
I tried this on TP-LINK TD-W8961ND (Ralink chipset:RT2860) and always stuck at M2 after getting the PKr, i think iT has something to do with wps version because Wash -i mon0 doesn't show Wps is enabled on the router but other tools on wifislax like WpsScan show that wps is not locked.
![screenshot_20150414174436](https://cloud.githubusercontent.com/assets/8457366/7215108/eeda5892-e5b6-11e4-8cf7-09eb4e6abba4.png)

**Comment by t6x** [comment]
This is because the router was configured to work only as the WPS button, it will respond only when the button is pressedThis not is a standard configuration of the router
Date: Sat, 18 Apr 2015 03:33:23 -0700

**Comment by Gitussef** [comment]
Ok thank you,is there a way to get PKe,AuthKey,E-Hash1 and E-Hash2 before M2?

**Comment by soxrok2212** [comment]
PKE and Authkey yes, the rest no.
