### ISSUE TITLE
wash: -C not working and [X] ERROR: sql_init failed when running prior to install

### ISSUE THREAD

**Issue by alexaraujo** [t6x/reaver-wps-fork-t6x#53]
The following error is printed by wash if one tries to run without installing it:

```
root@kali:~/reaver-wps-fork-t6x/src# ./wash
[X] ERROR: sql_init failed
root@kali:~/reaver-wps-fork-t6x/src# ./wash -h
[X] ERROR: sql_init failed
root@kali:~/reaver-wps-fork-t6x/src# ./wash -i wlan0mon -C
[X] ERROR: sql_init failed

```

In my case, sql_init() is looking for reaver.db in /usr/local/etc/reaver directory. But without doing make install prior to running wash, reaver.db won't be found and sqlite3_open() is going to raise an exception. I think it is worth adding some verification - testing whether the file actually exists or not -  prior to calling sqlite3_open(). And in case of failure it could try to open the reaver.db in the same directory as wash is being executed.

Also, it looks like -C swith is being ignored as in the example bellow:

```
root@kali:~/reaver-wps-fork-t6x/src# ./wash -i wlan0mon -C
[!] Found packet with bad FCS, skipping...
[!] Found packet with bad FCS, skipping...

```

**Comment by kcdtv** [comment]
About the -C tag :
   It is now enabled by default. 
If you use it you will disabled it.
   I am not really sure if that is on purpose or not. :smiley_cat:
