### ISSUE TITLE
error: pcap library not found! 

### ISSUE THREAD

**Issue by eminmammadov** [t6x/reaver-wps-fork-t6x#54]
root@root:~/reaver-wps-fork-t6x/src# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for pcap_open_live in -lpcap... no
**## error: pcap library not found! **(what is?)

**Comment by crushedice2000** [comment]
@eminmammadov:

1. Please, when you paste code or terminal output in GitHub, prepend four spaces to each line. If you do this, the block will be monospaced. [See the markdown reference](https://help.github.com/categories/writing-on-github/). :smile: 

2. Quote from [The Bible of Reaver](https://github.com/t6x/reaver-wps-fork-t6x/blob/master/docs/README)  (lines 41-50): :smiling_imp: 

    > Reaver is only supported on the Linux platform, requires the libpcap and libsqlite3 libraries, and can be built and installed by running:

    >     ./configure
    >     make
    >     sudo make install

    > To remove everything installed/created by Reaver:

    >     sudo make distclean

3. You can install these libraries with these methods:

    + For Debian-based systems:

            sudo apt-get install sqlite3 libsqlite3-dev libpcap0.8-dev

**Comment by soxrok2212** [comment]
Thanks

**Comment by eminmammadov** [comment]
@crushedice2000 Thanks my friend.

**Comment by crushedice2000** [comment]
@eminmammadov @soxrok2212 : You're welcome!

**Comment by jovanymezura** [comment]
still working
