### ISSUE TITLE
Reaver with macchanger (or manual mac change)

### ISSUE THREAD

**Issue by hersgori** [t6x/reaver-wps-fork-t6x#55]
Debian 8.2 / Kali Linux 2016.1
Reaver 1.5.2 mod by t6_x and others
Command:
sudo reaver -i *interface* -b *mac* -c *channel* -vvv    (+ any arguments like N S K etc.)
gives output like:
WARNING: Failed to associate with *mac* (ESSID: *essid*)
when mac of wlan0 and wlan0mon (mon0) was changed manualy or with macchanger. If mac is real reaver works perfectly. 
In case of using aircrack-ng packet:
aireplay-ng -1 0 -a *mac* *interface*
and using "-A" argument in reaver, programm goes to detect WPS pin but stops every time pin's detected.

**Comment by soxrok2212** [comment]
You need to tell Reaver you are spoofing your mac: https://github.com/t6x/reaver-wps-fork-t6x#reaver-usage
