### ISSUE TITLE
error during make 

### ISSUE THREAD

**Issue by darkworks** [t6x/reaver-wps-fork-t6x#56]
i got error when i run make command after configure , on kali sana 2.0

```
2 -Ilibwps wpscrack.c *.o libwps/*.o wps/*.o tls/bignum.o tls/libtls.a utils/libutils.a crypto/libcrypto.a lwe/libiw.a -ldl -lm -lpcap -lsqlite3  -o reaver
wpscrack.c: In function ‘main’:
wpscrack.c:40:33: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
     int ret_val = EXIT_FAILURE, r = 0;
                                 ^

```

**Comment by aanarchyy** [comment]
You got a warning, not an error.

**Comment by darkworks** [comment]
hmmmm then why make process stopped  , i mean after that if i do make install , it not work

**Comment by kcdtv** [comment]
Could you put here the exact (full) stdout of both commands?
If you have an error while compiling you will have an error message at the end, so it is important for us to see everything that happens in your shell
Cheers

**Comment by profedrini** [comment]
It's a warning. Compilation stopped but you should get the executable on the current directory

Run    ./reaver  after compilation stops
