### ISSUE TITLE
Cannot change MAC of the host system

### ISSUE THREAD

**Issue by Daniyal-Javani** [t6x/reaver-wps-fork-t6x#61]
When I use `-m` flag nothing changed. I create a filter on WiFi router and when I use `-m` flag with a white list mac address, nothing changed and still stuck on `Starting Cracking Session. Pin count: 0, Max pin attempts: 11000` with `$ sudo reaver -i wlan0mon -b xxxxxxxxxxx -c 1 -vv -K -f -w` command.
Is there any other way? I try macchanger but have the same issue.

**Comment by soxrok2212** [comment]
You need to spoof both the monitor interface and use the -m flag in Reaver.
