### ISSUE TITLE
Incorporating patches for big-endian machines

### ISSUE THREAD

**Issue by yousong** [t6x/reaver-wps-fork-t6x#66]
Hi, there are several patches for the old reaver project maintained in OpenWrt packages feed.  One of them is about endian-conversion on BE machines [1].  It seemed that the issue is also not fixed in the fork here.  Can you give these patches a look and see if they are fit for inclusion?  All these patches are signed-off-by the respective authors so there should be no license issues.

[1] https://github.com/openwrt/packages/blob/master/net/reaver/patches/0001-wpscrack-big-endian-fixes.patch

**Comment by rofl0r** [comment]
closed by e671b44cbd314431bd706de57d8a6b5b871fbb60
