### ISSUE TITLE
Print first half of the PIN when it is guessed

### ISSUE THREAD

**Issue by drws** [t6x/reaver-wps-fork-t6x#83]
This is an enhancment/feature suggestion to make reaver output the first half of the PIN (4 digits) when it is cracked in order to notify the user of an advancement.

**Comment by kcdtv** [comment]
Hi drws!
 You can see that at any moment just by checking your stdout :smiley_cat: 
When the first half is found the brute force is done on p2 and not on p1. 
 You can see also that you get M5-M6 packets after obtaining the first half. you can see that the first half doesn't change but the second one, you also have the percentage of crack that jumps from something to 90%....  
  There is no room for mistake here if the user understands the basis of the attack
