### ISSUE TITLE
Maybe a bug or not with PixieWPS?

### ISSUE THREAD

**Issue by Open1029** [t6x/reaver-wps-fork-t6x#97]
I'm trying to hack a router maybe vulnerable by pixie dust attack...

So I launch reaver with this parameters:

`reaver  -I wlan0mon -b XX:XX:XX:XX:XX:XX -e ESSID -c 1 -K 1 -l 10 -t 10 -g 1 -vv` 

![Reaver Attack](http://i66.tinypic.com/x0uqeb.png)

After that, when there is reaver cmd attack it stay freeze like in the pic...

So I try to copy and paste the command that reaver is trying to execute, but in another terminal...

`reaver  -I wlan0mon -b XX:XX:XX:XX:XX:XX -c 1 -s y -vv -p 12345670`

But reaver, differently  @from the reaver cmd line attack, returns me errors like in image: 

`[+] Sending EAPOL START request
  [!] Warning: Receive timeout occurred
` 

![Reaver Attack](http://i64.tinypic.com/24gpn9f.png)

p.s: I noticied sometimes after my attacks router change his channel... 

so is it maybe a bug of reaver with pixiewps? Or what can I do against this router , for example?

Thank you so much!

**Comment by kcdtv** [comment]
That's not a bug 
You are not in correct conditions (interferences, weak signal) to do a correct ful WPS exchange.
Cheers

**Comment by kcdtv** [comment]
Pixiewps attack is done without even fully checking the first half of the PIN, 
You should read the thread of soxrock2212 about pixie dust attack in kali forum. 
Remember that this is a GitHub repository mainly to speak about code issues.
Not a forum about WiFi hacking
